import { Injectable, computed, signal } from '@angular/core';

interface Language {
  code: string;
  name: string;
  dir: 'ltr' | 'rtl';
}

// Configuration for available languages.
const AVAILABLE_LANGUAGES: readonly Language[] = [
  { code: 'en', name: 'English', dir: 'ltr' },
  { code: 'ar', name: 'عربي', dir: 'rtl' },
  { code: 'fr', name: 'Français', dir: 'ltr' },
  { code: 'es', name: 'Español', dir: 'ltr' },
  { code: 'zh', name: '中文', dir: 'ltr' },
  { code: 'hi', name: 'हिन्दी', dir: 'ltr' },
  { code: 'bn', name: 'বাংলা', dir: 'ltr' },
];

// --- INLINE TRANSLATION DATA STORE ---
// All translations are now embedded directly in the application.
// This eliminates all network requests for language files, making the app
// faster, more reliable, and immune to deployment environment issues.
const _translationData: Readonly<Record<string, Record<string, string>>> = {
  en: {
    "APP_TITLE": "Buaziz Snaploader",
    "HEADER_TITLE_PART_1": "Buaziz",
    "HEADER_TITLE_PART_2": "SnapLoader",
    "HEADER_SUBTITLE": "Your memories, unlocked. 🔓",
    "FILE_UPLOAD_TITLE": "Feed the Ghost Your File 👻",
    "FILE_UPLOAD_DESCRIPTION": "Drop your Snapchat export <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">.zip</code> file or just the <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">memories_history.html</code> file to begin! ✨",
    "FILE_UPLOAD_HELP_LINK": "❓ How do I get this file?",
    "FILE_UPLOAD_BUTTON": "Select File",
    "UPLOAD_NEW_FILE_BUTTON": "Upload New File",
    "PARSING_MESSAGE": "Reading your memories...",
    "PLEASE_WAIT": "Just a moment...",
    "GEOCODING_MESSAGE": "Figuring out where you've been... 🌍",
    "GEOCODING_REMAINING": "Remaining ⏳",
    "MEMORIES_TO_PROCESS": "memories to process",
    "FOUND_LOCATIONS": "Places You've Been 📍",
    "SEARCHING_FOR_LOCATIONS": "Searching for locations...",
    "CANCEL": "Cancel",
    "CANCELLING_GEOCODING": "Stopping location search...",
    "CANCELLING_DOWNLOAD": "Cancelling...",
    "BY_YEAR": "🗓️ By Year",
    "BY_COUNTRY": "🌍 By Country",
    "SELECTION_SUMMARY": "You're grabbing <span class=\"font-bold text-snap-yellow\">{{count}}</span> memories (<span class=\"font-semibold text-white\">{{photos}}</span> photos, <span class=\"font-semibold text-white\">{{videos}}</span> videos).",
    "START_DOWNLOAD": "Let's Go! 🪄",
    "TOTAL_MEMORIES": "📚 Total Memories",
    "PHOTOS": "🖼️ Photos",
    "VIDEOS": "📹 Videos",
    "COMPLETE_TITLE": "All Done! 🎉",
    "COMPLETE_SUBTITLE": "Your memories are packed in <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">{{filename}}</code> and ready to go!",
    "COMPLETE_DOWNLOAD_BUTTON": "💾 Download ZIP",
    "COMPLETE_START_OVER_BUTTON": "🔄 Go Again",
    "ERROR_TITLE": "Uh Oh... 😟",
    "ERROR_RETRY_BUTTON": "🔄 Try Again",
    "ERROR_NO_MEMORIES_FOUND": "No memories were found in the selected file. Please check the file and try again.",
    "ERROR_INVALID_FILE": "Failed to process file. Please ensure it is a valid memories_history.html or a valid Snapchat data export ZIP.",
    "ERROR_NO_HTML_IN_ZIP": "The uploaded ZIP file does not contain 'memories_history.html'. Please check the file and try again.",
    "ERROR_INVALID_FILE_TYPE": "Invalid file type. Please upload your .zip export file or the memories_history.html file.",
    "UNZIPPING_FILE": "Extracting your memories file...",
    "ERROR_ZIP_CREATION": "An error occurred while creating the ZIP file.",
    "CREATING_ZIP": "Packing your memories...",
    "FINALIZING_ZIP": "Putting a bow on it...",
    "PREPARING_DOWNLOAD": "Getting ready...",
    "DOWNLOAD_HEADLINE_DEFAULT": "Downloading your memories...",
    "DOWNLOAD_HEADLINE_YEAR": "🗓️ Grabbing memories from {{selection}}",
    "DOWNLOAD_HEADLINE_COUNTRY": "🌍 Grabbing memories from {{selection}}",
    "PROGRESS_COMPLETED": "✅ Done",
    "PROGRESS_PENDING": "⏳ Waiting",
    "PROGRESS_FAILED": "❌ Failed",
    "PROGRESS_TOTAL": "🔢 Total",
    "PROGRESS_PROCESSING_FILES": "⚙️ Working On It...",
    "YEAR_SELECT_TITLE": "🗓️ Pick a Year",
    "YEAR_TABLE_HEADER_YEAR": "📅 Year",
    "YEAR_TABLE_HEADER_PHOTOS": "🖼️ Photos",
    "YEAR_TABLE_HEADER_VIDEOS": "📹 Videos",
    "YEAR_TABLE_HEADER_TOTAL": "📦 Total",
    "MONTH_SELECT_TITLE": "🗓️ Select Months in {{year}}",
    "MONTH_TABLE_HEADER_MONTH": "📅 Month",
    "BACK_TO_YEARS": "Back to Years",
    "YEAR_SELECT_FOR_COUNTRY_TITLE": "🗓️ Select Years in {{country}}",
    "BACK_TO_COUNTRIES": "Back to Countries",
    "DOWNLOAD_HISTORY_NOTE": "Downloaded: {{downloaded}}/{{total}}",
    "COUNTRY_SELECT_TITLE": "🌍 Pick a Country",
    "COUNTRY_TABLE_HEADER_COUNTRY": "🗺️ Country",
    "COUNTRY_TABLE_HEADER_TOTAL": "🔢 Total",
    "COUNTRY_NO_LOCATIONS": "No locations found.",
    "NO_LOCATION_DATA": "No Location Data",
    "LOCATION_NOT_IDENTIFIED": "Mystery Location",
    "API_ERROR": "API Error",
    "LINKS_VALID_UNTIL": "Links are valid until {{date}}",
    "LINKS_EXPIRE_SOON": "Warning: Links expire soon (on {{date}})",
    "LINKS_EXPIRED_ON": "Links expired on {{date}}",
    "EXPIRED_LINKS_TITLE": "Download Links Have Expired",
    "EXPIRED_LINKS_DESCRIPTION": "The download links in your <code>memories_history.html</code> file are only valid for 7 days after you export your data from Snapchat. To continue, you must request a new \"My Data\" export to get fresh links.",
    "STATUS_RETRYING": "⏳ Retrying... (Attempt {{attempt}} of {{max}})",
    "STATUS_EMBEDDING": "⏳ Embedding metadata...",
    "STATUS_MERGING": "⏳ Merging images...",
    "STATUS_DOWNLOADING_OVERLAY": "⏳ Downloading overlay...",
    "STATUS_DOWNLOADING": "⏳ Downloading...",
    "STATUS_COMPLETED": "✅ Completed",
    "STATUS_FAILED": "❌ Download failed",
    "STATUS_QUEUED": "🕒 Queued for download",
    "ZIP_FILENAME_PATTERN": "snapchat-memories-{{mode}}-{{selection}}.zip",
    "ZIP_FILENAME_DEFAULT": "snapchat-memories.zip",
    "LARGE_SELECTION_WARNING": "This large selection will be downloaded as multiple smaller ZIP files for reliability.",
    "ZIP_FILENAME_PATTERN_BATCH": "snapchat-memories-{{mode}}-{{selection}}-part-{{current}}-of-{{total}}.zip",
    "PROCESSING_PART": "📦 Processing Part {{current}} of {{total}}",
    "BATCH_CONTROL_TITLE": "Batch Download Control",
    "BATCH_CONTROL_SUBTITLE": "Your selection has been divided into {{count}} parts. Process them individually or all at once to create the downloadable ZIP files.",
    "DOWNLOAD_ALL_BUTTON": "Download All ({{count}})",
    "PROCESS_ALL_BUTTON": "Process All ({{count}})",
    "PART_STATUS_LABEL": "Part {{current}} of {{total}}",
    "DOWNLOAD_BUTTON": "Download",
    "RETRY_BUTTON": "Retry",
    "PROCESS_BUTTON": "Process",
    "STATUS_LABEL_SUCCESS": "Success",
    "STATUS_LABEL_FAILED": "Failed",
    "STATUS_LABEL_PROCESSING": "Processing...",
    "STATUS_LABEL_PLANNED": "Ready to Process",
    "REPORT_TITLE": "Snaploader Download Report",
    "REPORT_BATCH_INFO": "Batch {{batchNum}} of {{totalBatches}} &bull; Generated on {{date}}",
    "REPORT_STAT_TOTAL": "Total Files",
    "REPORT_STAT_SUCCESSFUL": "Successful",
    "REPORT_STAT_FAILED": "Failed",
    "REPORT_FAILED_MEMORIES_TITLE": "Failed Memories ({{count}})",
    "REPORT_FAILED_MEMORIES_SUBTITLE": "These files could not be downloaded or processed. You may need to request a new data export from Snapchat if the links have expired.",
    "REPORT_FOOTER_TEXT": "Generated by Snaploader &bull; ",
    "REPORT_FOOTER_LINK": "Create your own ZIP",
    "PENDING_GEOCODING": "Pending...",
    "COUNTRY_UNKNOWN": "Unknown",
    "MONTH_JANUARY": "January",
    "MONTH_FEBRUARY": "February",
    "MONTH_MARCH": "March",
    "MONTH_APRIL": "April",
    "MONTH_MAY": "May",
    "MONTH_JUNE": "June",
    "MONTH_JULY": "July",
    "MONTH_AUGUST": "August",
    "MONTH_SEPTEMBER": "September",
    "MONTH_OCTOBER": "October",
    "MONTH_NOVEMBER": "November",
    "MONTH_DECEMBER": "December",
    "Afghanistan": "Afghanistan",
    "Angola": "Angola",
    "Albania": "Albania",
    "United Arab Emirates": "United Arab Emirates",
    "Argentina": "Argentina",
    "Armenia": "Armenia",
    "Antarctica": "Antarctica",
    "French Southern and Antarctic Lands": "French Southern and Antarctic Lands",
    "Australia": "Australia",
    "Austria": "Austria",
    "Azerbaijan": "Azerbaijan",
    "Burundi": "Burundi",
    "Belgium": "Belgium",
    "Benin": "Benin",
    "Burkina Faso": "Burkina Faso",
    "Bangladesh": "Bangladesh",
    "Bulgaria": "Bulgaria",
    "The Bahamas": "The Bahamas",
    "Bosnia and Herzegovina": "Bosnia and Herzegovina",
    "Belarus": "Belarus",
    "Belize": "Belize",
    "Bermuda": "Bermuda",
    "Bolivia": "Bolivia",
    "Brazil": "Brazil",
    "Brunei": "Brunei",
    "Bhutan": "Bhutan",
    "Botswana": "Botswana",
    "Central African Republic": "Central African Republic",
    "Canada": "Canada",
    "Switzerland": "Switzerland",
    "Chile": "Chile",
    "China": "China",
    "Ivory Coast": "Ivory Coast",
    "Cameroon": "Cameroon",
    "Democratic Republic of the Congo": "Democratic Republic of the Congo",
    "Republic of the Congo": "Republic of the Congo",
    "Colombia": "Colombia",
    "Costa Rica": "Costa Rica",
    "Cuba": "Cuba",
    "Northern Cyprus": "Northern Cyprus",
    "Cyprus": "Cyprus",
    "Czechia": "Czechia",
    "Germany": "Germany",
    "Djibouti": "Djibouti",
    "Denmark": "Denmark",
    "Dominican Republic": "Dominican Republic",
    "Algeria": "Algeria",
    "Ecuador": "Ecuador",
    "Egypt": "Egypt",
    "Eritrea": "Eritrea",
    "Spain": "Spain",
    "Estonia": "Estonia",
    "Ethiopia": "Ethiopia",
    "Finland": "Finland",
    "Fiji": "Fiji",
    "Falkland Islands": "Falkland Islands",
    "France": "France",
    "Gabon": "Gabon",
    "United Kingdom": "United Kingdom",
    "Georgia": "Georgia",
    "Ghana": "Ghana",
    "Guinea": "Guinea",
    "Gambia": "Gambia",
    "Guinea-Bissau": "Guinea-Bissau",
    "Equatorial Guinea": "Equatorial Guinea",
    "Greece": "Greece",
    "Greenland": "Greenland",
    "Guatemala": "Guatemala",
    "Guyana": "Guyana",
    "Honduras": "Honduras",
    "Croatia": "Croatia",
    "Haiti": "Haiti",
    "Hungary": "Hungary",
    "Indonesia": "Indonesia",
    "India": "India",
    "Ireland": "Ireland",
    "Iran": "Iran",
    "Iraq": "Iraq",
    "Iceland": "Iceland",
    "Israel": "Israel",
    "Italy": "Italy",
    "Jamaica": "Jamaica",
    "Jordan": "Jordan",
    "Japan": "Japan",
    "Kazakhstan": "Kazakhstan",
    "Kenya": "Kenya",
    "Kyrgyzstan": "Kyrgyzstan",
    "Cambodia": "Cambodia",
    "South Korea": "South Korea",
    "Kosovo": "Kosovo",
    "Kuwait": "Kuwait",
    "Laos": "Laos",
    "Lebanon": "Lebanon",
    "Liberia": "Liberia",
    "Libya": "Libya",
    "Sri Lanka": "Sri Lanka",
    "Lesotho": "Lesotho",
    "Lithuania": "Lithuania",
    "Luxembourg": "Luxembourg",
    "Latvia": "Latvia",
    "Morocco": "Morocco",
    "Moldova": "Moldova",
    "Madagascar": "Madagascar",
    "Mexico": "Mexico",
    "Macedonia": "Macedonia",
    "Mali": "Mali",
    "Myanmar": "Myanmar",
    "Montenegro": "Montenegro",
    "Mongolia": "Mongolia",
    "Mozambique": "Mozambique",
    "Mauritania": "Mauritania",
    "Malawi": "Malawi",
    "Malaysia": "Malaysia",
    "Namibia": "Namibia",
    "New Caledonia": "New Caledonia",
    "Niger": "Niger",
    "Nigeria": "Nigeria",
    "Nicaragua": "Nicaragua",
    "Netherlands": "Netherlands",
    "Norway": "Norway",
    "Nepal": "Nepal",
    "New Zealand": "New Zealand",
    "Oman": "Oman",
    "Pakistan": "Pakistan",
    "Panama": "Panama",
    "Peru": "Peru",
    "Philippines": "Philippines",
    "Papua New Guinea": "Papua New Guinea",
    "Poland": "Poland",
    "Puerto Rico": "Puerto Rico",
    "North Korea": "North Korea",
    "Portugal": "Portugal",
    "Paraguay": "Paraguay",
    "Qatar": "Qatar",
    "Romania": "Romania",
    "Russia": "Russia",
    "Rwanda": "Rwanda",
    "Western Sahara": "Western Sahara",
    "Saudi Arabia": "Saudi Arabia",
    "Sudan": "Sudan",
    "South Sudan": "South Sudan",
    "Senegal": "Senegal",
    "Solomon Islands": "Solomon Islands",
    "Sierra Leone": "Sierra Leone",
    "El Salvador": "El Salvador",
    "Somaliland": "Somaliland",
    "Somalia": "Somalia",
    "Republic of Serbia": "Republic of Serbia",
    "Suriname": "Suriname",
    "Slovakia": "Slovakia",
    "Slovenia": "Slovenia",
    "Sweden": "Sweden",
    "Swaziland": "Swaziland",
    "Syria": "Syria",
    "Chad": "Chad",
    "Togo": "Togo",
    "Thailand": "Thailand",
    "Tajikistan": "Tajikistan",
    "Turkmenistan": "Turkmenistan",
    "East Timor": "East Timor",
    "Trinidad and Tobago": "Trinidad and Tobago",
    "Tunisia": "Tunisia",
    "Turkey": "Turkey",
    "Taiwan": "Taiwan",
    "Tanzania": "Tanzania",
    "Uganda": "Uganda",
    "Ukraine": "Ukraine",
    "Uruguay": "Uruguay",
    "United States of America": "United States of America",
    "Uzbekistan": "Uzbekistan",
    "Venezuela": "Venezuela",
    "Vietnam": "Vietnam",
    "Vanuatu": "Vanuatu",
    "West Bank": "West Bank",
    "Yemen": "Yemen",
    "South Africa": "South Africa",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabwe"
  },
  ar: {
    "APP_TITLE": "بوعزيز سناب لودر",
    "HEADER_TITLE_PART_1": "بوعزيز",
    "HEADER_TITLE_PART_2": "سناب لودر",
    "HEADER_SUBTITLE": "ذكرياتك، بمتناول يدك. 🔓",
    "FILE_UPLOAD_TITLE": "أطعم الشبح ملفك 👻",
    "FILE_UPLOAD_DESCRIPTION": "اسقط ملف <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">.zip</code> الخاص بتصدير سناب شات أو ملف <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">memories_history.html</code> هنا للبدء! ✨",
    "FILE_UPLOAD_HELP_LINK": "❓ كيف أحصل على هذا الملف؟",
    "FILE_UPLOAD_BUTTON": "اختر ملف",
    "UPLOAD_NEW_FILE_BUTTON": "تحميل ملف جديد",
    "PARSING_MESSAGE": "جاري قراءة ذكرياتك...",
    "PLEASE_WAIT": "لحظة من فضلك...",
    "GEOCODING_MESSAGE": "نكتشف أين كنت... 🌍",
    "GEOCODING_REMAINING": "المتبقي ⏳",
    "MEMORIES_TO_PROCESS": "ذكريات للمعالجة",
    "FOUND_LOCATIONS": "الأماكن التي زرتها 📍",
    "SEARCHING_FOR_LOCATIONS": "جاري البحث عن المواقع...",
    "CANCEL": "إلغاء",
    "CANCELLING_GEOCODING": "جاري إيقاف البحث عن المواقع...",
    "CANCELLING_DOWNLOAD": "جاري الإلغاء...",
    "BY_YEAR": "🗓️ حسب السنة",
    "BY_COUNTRY": "🌍 حسب البلد",
    "SELECTION_SUMMARY": "أنت على وشك تحميل <span class=\"font-bold text-snap-yellow\">{{count}}</span> من الذكريات (<span class=\"font-semibold text-white\">{{photos}}</span> صور, <span class=\"font-semibold text-white\">{{videos}}</span> فيديوهات).",
    "START_DOWNLOAD": "لننطلق! 🚀",
    "TOTAL_MEMORIES": "📚 مجموع الذكريات",
    "PHOTOS": "🖼️ صور",
    "VIDEOS": "📹 فيديوهات",
    "COMPLETE_TITLE": "اكتمل كل شيء! 🎉",
    "COMPLETE_SUBTITLE": "ذكرياتك معبأة في <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">{{filename}}</code> وجاهزة للانطلاق!",
    "COMPLETE_DOWNLOAD_BUTTON": "💾 تنزيل ZIP",
    "COMPLETE_START_OVER_BUTTON": "🔄 ابدأ من جديد",
    "ERROR_TITLE": "أوه أوه... 😟",
    "ERROR_RETRY_BUTTON": "🔄 حاول مرة أخرى",
    "ERROR_NO_MEMORIES_FOUND": "لم يتم العثور على ذكريات في الملف المحدد. يرجى التحقق من الملف والمحاولة مرة أخرى.",
    "ERROR_INVALID_FILE": "فشل في معالجة الملف. يرجى التأكد من أنه ملف memories_history.html صالح أو ملف تصدير بيانات سناب شات ZIP صالح.",
    "ERROR_NO_HTML_IN_ZIP": "الملف المضغوط الذي تم تحميله لا يحتوي على 'memories_history.html'. يرجى التحقق من الملف والمحاولة مرة أخرى.",
    "ERROR_INVALID_FILE_TYPE": "نوع ملف غير صالح. يرجى تحميل ملف التصدير .zip الخاص بك أو ملف memories_history.html.",
    "UNZIPPING_FILE": "جاري استخراج ملف ذكرياتك...",
    "ERROR_ZIP_CREATION": "حدث خطأ أثناء إنشاء ملف ZIP.",
    "CREATING_ZIP": "جاري حزم ذكرياتك...",
    "FINALIZING_ZIP": "نضع اللمسات الأخيرة...",
    "PREPARING_DOWNLOAD": "جاري الاستعداد...",
    "DOWNLOAD_HEADLINE_DEFAULT": "جاري تنزيل ذكرياتك...",
    "DOWNLOAD_HEADLINE_YEAR": "🗓️ جاري جلب الذكريات من {{selection}}",
    "DOWNLOAD_HEADLINE_COUNTRY": "🌍 جاري جلب الذكريات من {{selection}}",
    "PROGRESS_COMPLETED": "✅ مكتمل",
    "PROGRESS_PENDING": "⏳ قيد الانتظار",
    "PROGRESS_FAILED": "❌ فشل",
    "PROGRESS_TOTAL": "🔢 المجموع",
    "PROGRESS_PROCESSING_FILES": "⚙️ جاري العمل...",
    "YEAR_SELECT_TITLE": "🗓️ اختر سنة",
    "YEAR_TABLE_HEADER_YEAR": "📅 السنة",
    "YEAR_TABLE_HEADER_PHOTOS": "🖼️ الصور",
    "YEAR_TABLE_HEADER_VIDEOS": "📹 الفيديوهات",
    "YEAR_TABLE_HEADER_TOTAL": "📦 المجموع",
    "MONTH_SELECT_TITLE": "🗓️ اختر الأشهر في {{year}}",
    "MONTH_TABLE_HEADER_MONTH": "📅 الشهر",
    "BACK_TO_YEARS": "العودة إلى السنوات",
    "YEAR_SELECT_FOR_COUNTRY_TITLE": "🗓️ اختر السنوات في {{country}}",
    "BACK_TO_COUNTRIES": "العودة إلى البلدان",
    "DOWNLOAD_HISTORY_NOTE": "تم التنزيل: {{downloaded}}/{{total}}",
    "COUNTRY_SELECT_TITLE": "🌍 اختر بلدًا",
    "COUNTRY_TABLE_HEADER_COUNTRY": "🗺️ البلد",
    "COUNTRY_TABLE_HEADER_TOTAL": "🔢 المجموع",
    "COUNTRY_NO_LOCATIONS": "لم يتم العثور على مواقع.",
    "NO_LOCATION_DATA": "لا توجد بيانات موقع",
    "LOCATION_NOT_IDENTIFIED": "موقع غامض",
    "API_ERROR": "خطأ في الواجهة البرمجية",
    "LINKS_VALID_UNTIL": "الروابط صالحة حتى {{date}}",
    "LINKS_EXPIRE_SOON": "تحذير: ستنتهي صلاحية الروابط قريبًا (في {{date}})",
    "LINKS_EXPIRED_ON": "انتهت صلاحية الروابط في {{date}}",
    "EXPIRED_LINKS_TITLE": "روابط التنزيل منتهية الصلاحية",
    "EXPIRED_LINKS_DESCRIPTION": "روابط التنزيل في ملف <code>memories_history.html</code> الخاص بك صالحة لمدة 7 أيام فقط بعد تصدير بياناتك من سناب شات. للمتابعة، يجب عليك طلب تصدير \"بياناتي\" جديد للحصول على روابط حديثة.",
    "STATUS_RETRYING": "⏳ جاري إعادة المحاولة... (محاولة {{attempt}} من {{max}})",
    "STATUS_EMBEDDING": "⏳ جاري تضمين البيانات الوصفية...",
    "STATUS_MERGING": "⏳ جاري دمج الصور...",
    "STATUS_DOWNLOADING_OVERLAY": "⏳ جاري تنزيل الطبقة الإضافية...",
    "STATUS_DOWNLOADING": "⏳ جاري التنزيل...",
    "STATUS_COMPLETED": "✅ مكتمل",
    "STATUS_FAILED": "❌ فشل التنزيل",
    "STATUS_QUEUED": "🕒 في قائمة الانتظار للتنزيل",
    "ZIP_FILENAME_PATTERN": "ذكريات-سناب-شات-{{mode}}-{{selection}}.zip",
    "ZIP_FILENAME_DEFAULT": "ذكريات-سناب-شات.zip",
    "LARGE_SELECTION_WARNING": "سيتم تنزيل هذا التحديد الكبير كملفات ZIP متعددة أصغر حجمًا لضمان الموثوقية.",
    "ZIP_FILENAME_PATTERN_BATCH": "ذكريات-سناب-شات-{{mode}}-{{selection}}-جزء-{{current}}-من-{{total}}.zip",
    "PROCESSING_PART": "📦 جاري معالجة الجزء {{current}} من {{total}}",
    "BATCH_CONTROL_TITLE": "لوحة تحكم تنزيل الدفعات",
    "BATCH_CONTROL_SUBTITLE": "تم تقسيم اختيارك إلى {{count}} أجزاء. قم بمعالجتها بشكل فردي أو دفعة واحدة لإنشاء ملفات ZIP القابلة للتنزيل.",
    "DOWNLOAD_ALL_BUTTON": "تنزيل الكل ({{count}})",
    "PROCESS_ALL_BUTTON": "معالجة الكل ({{count}})",
    "PART_STATUS_LABEL": "الجزء {{current}} من {{total}}",
    "DOWNLOAD_BUTTON": "تنزيل",
    "RETRY_BUTTON": "إعادة المحاولة",
    "PROCESS_BUTTON": "معالجة",
    "STATUS_LABEL_SUCCESS": "نجاح",
    "STATUS_LABEL_FAILED": "فشل",
    "STATUS_LABEL_PROCESSING": "جاري المعالجة...",
    "STATUS_LABEL_PLANNED": "جاهز للمعالجة",
    "REPORT_TITLE": "تقرير تحميل سناب لودر",
    "REPORT_BATCH_INFO": "دفعة {{batchNum}} من {{totalBatches}} &bull; تم إنشاؤه في {{date}}",
    "REPORT_STAT_TOTAL": "إجمالي الملفات",
    "REPORT_STAT_SUCCESSFUL": "ناجح",
    "REPORT_STAT_FAILED": "فشل",
    "REPORT_FAILED_MEMORIES_TITLE": "الذكريات الفاشلة ({{count}})",
    "REPORT_FAILED_MEMORIES_SUBTITLE": "تعذر تنزيل هذه الملفات أو معالجتها. قد تحتاج إلى طلب تصدير بيانات جديد من سناب شات إذا انتهت صلاحية الروابط.",
    "REPORT_FOOTER_TEXT": "تم إنشاؤه بواسطة سناب لودر &bull; ",
    "REPORT_FOOTER_LINK": "أنشئ ملف ZIP الخاص بك",
    "PENDING_GEOCODING": "قيد الانتظار...",
    "COUNTRY_UNKNOWN": "غير معروف",
    "MONTH_JANUARY": "يناير",
    "MONTH_FEBRUARY": "فبراير",
    "MONTH_MARCH": "مارس",
    "MONTH_APRIL": "أبريل",
    "MONTH_MAY": "مايو",
    "MONTH_JUNE": "يونيو",
    "MONTH_JULY": "يوليو",
    "MONTH_AUGUST": "أغسطس",
    "MONTH_SEPTEMBER": "سبتمبر",
    "MONTH_OCTOBER": "أكتوبر",
    "MONTH_NOVEMBER": "نوفمبر",
    "MONTH_DECEMBER": "ديسمبر",
    "Afghanistan": "أفغانستان",
    "Angola": "أنغولا",
    "Albania": "ألبانيا",
    "United Arab Emirates": "الإمارات العربية المتحدة",
    "Argentina": "الأرجنتين",
    "Armenia": "أرمينيا",
    "Antarctica": "القارة القطبية الجنوبية",
    "French Southern and Antarctic Lands": "الأراضي الفرنسية الجنوبية وأنتارتيكا",
    "Australia": "أستراليا",
    "Austria": "النمسا",
    "Azerbaijan": "أذربيجان",
    "Burundi": "بوروندي",
    "Belgium": "بلجيكا",
    "Benin": "بنين",
    "Burkina Faso": "بوركينا فاسو",
    "Bangladesh": "بنغلاديش",
    "Bulgaria": "بلغاريا",
    "The Bahamas": "جزر البهاما",
    "Bosnia and Herzegovina": "البوسنة والهرسك",
    "Belarus": "بيلاروسيا",
    "Belize": "بليز",
    "Bermuda": "برمودا",
    "Bolivia": "بوليفيا",
    "Brazil": "البرازيل",
    "Brunei": "بروناي",
    "Bhutan": "بوتان",
    "Botswana": "بوتسوانا",
    "Central African Republic": "جمهورية أفريقيا الوسطى",
    "Canada": "كندا",
    "Switzerland": "سويسرا",
    "Chile": "تشيلي",
    "China": "الصين",
    "Ivory Coast": "ساحل العاج",
    "Cameroon": "الكاميرون",
    "Democratic Republic of the Congo": "جمهورية الكونغو الديمقراطية",
    "Republic of the Congo": "جمهورية الكونغو",
    "Colombia": "كولومبيا",
    "Costa Rica": "كوستاريكا",
    "Cuba": "كوبا",
    "Northern Cyprus": "شمال قبرص",
    "Cyprus": "قبرص",
    "Czechia": "التشيك",
    "Germany": "ألمانيا",
    "Djibouti": "جيبوتي",
    "Denmark": "الدنمارك",
    "Dominican Republic": "جمهورية الدومينيكان",
    "Algeria": "الجزائر",
    "Ecuador": "الإكوادور",
    "Egypt": "مصر",
    "Eritrea": "إريتريا",
    "Spain": "إسبانيا",
    "Estonia": "إستونيا",
    "Ethiopia": "إثيوبيا",
    "Finland": "فنلندا",
    "Fiji": "فيجي",
    "Falkland Islands": "جزر فوكلاند",
    "France": "فرنسا",
    "Gabon": "الغابون",
    "United Kingdom": "المملكة المتحدة",
    "Georgia": "جورجيا",
    "Ghana": "غانا",
    "Guinea": "غينيا",
    "Gambia": "غامبيا",
    "Guinea-Bissau": "غينيا بيساو",
    "Equatorial Guinea": "غينيا الاستوائية",
    "Greece": "اليونان",
    "Greenland": "جرينلاند",
    "Guatemala": "غواتيمالا",
    "Guyana": "غيانا",
    "Honduras": "هندوراس",
    "Croatia": "كرواتيا",
    "Haiti": "هايتي",
    "Hungary": "المجر",
    "Indonesia": "إندونيسيا",
    "India": "الهند",
    "Ireland": "أيرلندا",
    "Iran": "إيران",
    "Iraq": "العراق",
    "Iceland": "آيسلندا",
    "Israel": "إسرائيل",
    "Italy": "إيطاليا",
    "Jamaica": "جامايكا",
    "Jordan": "الأردن",
    "Japan": "اليابان",
    "Kazakhstan": "كازاخستان",
    "Kenya": "كينيا",
    "Kyrgyzstan": "قيرغيزستان",
    "Cambodia": "كمبوديا",
    "South Korea": "كوريا الجنوبية",
    "Kosovo": "كوسوفو",
    "Kuwait": "الكويت",
    "Laos": "لاوس",
    "Lebanon": "لبنان",
    "Liberia": "ليبيريا",
    "Libya": "ليبيا",
    "Sri Lanka": "سريلانكا",
    "Lesotho": "ليسوتو",
    "Lithuania": "ليتوانيا",
    "Luxembourg": "لوكسمبورغ",
    "Latvia": "لاتفيا",
    "Morocco": "المغرب",
    "Moldova": "مولدوفا",
    "Madagascar": "مدغشقر",
    "Mexico": "المكسيك",
    "Macedonia": "مقدونيا",
    "Mali": "مالي",
    "Myanmar": "ميانمار",
    "Montenegro": "الجبل الأسود",
    "Mongolia": "منغوليا",
    "Mozambique": "موزمبيق",
    "Mauritania": "موريتانيا",
    "Malawi": "مالاوي",
    "Malaysia": "ماليزيا",
    "Namibia": "ناميبيا",
    "New Caledonia": "كاليدونيا الجديدة",
    "Niger": "النيجر",
    "Nigeria": "نيجيريا",
    "Nicaragua": "نيكاراغوا",
    "Netherlands": "هولندا",
    "Norway": "النرويج",
    "Nepal": "نيبال",
    "New Zealand": "نيوزيلندا",
    "Oman": "عمان",
    "Pakistan": "باكستان",
    "Panama": "بنما",
    "Peru": "بيرو",
    "Philippines": "الفلبين",
    "Papua New Guinea": "بابوا غينيا الجديدة",
    "Poland": "بولندا",
    "Puerto Rico": "بورتوريكو",
    "North Korea": "كوريا الشمالية",
    "Portugal": "البرتغال",
    "Paraguay": "باراغواي",
    "Qatar": "قطر",
    "Romania": "رومانيا",
    "Russia": "روسيا",
    "Rwanda": "رواندا",
    "Western Sahara": "الصحراء الغربية",
    "Saudi Arabia": "المملكة العربية السعودية",
    "Sudan": "السودان",
    "South Sudan": "جنوب السودان",
    "Senegal": "السنغال",
    "Solomon Islands": "جزر سليمان",
    "Sierra Leone": "سيراليون",
    "El Salvador": "السلفادور",
    "Somaliland": "صوماليلاند",
    "Somalia": "الصومال",
    "Republic of Serbia": "جمهورية صربيا",
    "Suriname": "سورينام",
    "Slovakia": "سلوفاكيا",
    "Slovenia": "سلوفينيا",
    "Sweden": "السويد",
    "Swaziland": "سوازيلاند",
    "Syria": "سوريا",
    "Chad": "تشاد",
    "Togo": "توغو",
    "Thailand": "تايلاند",
    "Tajikistan": "طاجيكستان",
    "Turkmenistan": "تركمانستان",
    "East Timor": "تيمور الشرقية",
    "Trinidad and Tobago": "ترينيداد وتوباغو",
    "Tunisia": "تونس",
    "Turkey": "تركيا",
    "Taiwan": "تايوان",
    "Tanzania": "تنزانيا",
    "Uganda": "أوغندا",
    "Ukraine": "أوكرانيا",
    "Uruguay": "أوروغواي",
    "United States of America": "الولايات المتحدة الأمريكية",
    "Uzbekistan": "أوزبكستان",
    "Venezuela": "فنزويلا",
    "Vietnam": "فيتنام",
    "Vanuatu": "فانواتو",
    "West Bank": "الضفة الغربية",
    "Yemen": "اليمن",
    "South Africa": "جنوب أفريقيا",
    "Zambia": "زامبيا",
    "Zimbabwe": "زيمبابوي"
  },
  fr: {
    "APP_TITLE": "Snaploader",
    "HEADER_TITLE_PART_1": "Snap",
    "HEADER_TITLE_PART_2": "Loader",
    "HEADER_SUBTITLE": "Vos souvenirs, déverrouillés. 🔓",
    "FILE_UPLOAD_TITLE": "Donnez votre fichier au fantôme 👻",
    "FILE_UPLOAD_DESCRIPTION": "Déposez votre fichier d'exportation Snapchat <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">.zip</code> ou simplement le fichier <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">memories_history.html</code> pour commencer ! ✨",
    "FILE_UPLOAD_HELP_LINK": "❓ Comment obtenir ce fichier ?",
    "FILE_UPLOAD_BUTTON": "Sélectionner un fichier",
    "UPLOAD_NEW_FILE_BUTTON": "Télécharger un nouveau fichier",
    "PARSING_MESSAGE": "Lecture de vos souvenirs...",
    "PLEASE_WAIT": "Juste un instant...",
    "GEOCODING_MESSAGE": "Découverte de vos destinations... 🌍",
    "GEOCODING_REMAINING": "Restant ⏳",
    "MEMORIES_TO_PROCESS": "souvenirs à traiter",
    "FOUND_LOCATIONS": "Lieux que vous avez visités 📍",
    "SEARCHING_FOR_LOCATIONS": "Recherche de lieux...",
    "CANCEL": "Annuler",
    "CANCELLING_GEOCODING": "Arrêt de la recherche de lieux...",
    "CANCELLING_DOWNLOAD": "Annulation...",
    "BY_YEAR": "🗓️ Par année",
    "BY_COUNTRY": "🌍 Par pays",
    "SELECTION_SUMMARY": "Vous récupérez <span class=\"font-bold text-snap-yellow\">{{count}}</span> souvenirs (<span class=\"font-semibold text-white\">{{photos}}</span> photos, <span class=\"font-semibold text-white\">{{videos}}</span> vidéos).",
    "START_DOWNLOAD": "C'est parti ! 🚀",
    "TOTAL_MEMORIES": "📚 Total des souvenirs",
    "PHOTOS": "🖼️ Photos",
    "VIDEOS": "📹 Vidéos",
    "COMPLETE_TITLE": "Terminé ! 🎉",
    "COMPLETE_SUBTITLE": "Vos souvenirs sont emballés dans <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">{{filename}}</code> et prêts à partir !",
    "COMPLETE_DOWNLOAD_BUTTON": "💾 Télécharger le ZIP",
    "COMPLETE_START_OVER_BUTTON": "🔄 Recommencer",
    "ERROR_TITLE": "Oh oh... 😟",
    "ERROR_RETRY_BUTTON": "🔄 Réessayer",
    "ERROR_NO_MEMORIES_FOUND": "Aucun souvenir trouvé dans le fichier sélectionné. Veuillez vérifier le fichier et réessayer.",
    "ERROR_INVALID_FILE": "Échec du traitement du fichier. Assurez-vous qu'il s'agit d'un fichier memories_history.html valide ou d'une archive ZIP d'exportation de données Snapchat valide.",
    "ERROR_NO_HTML_IN_ZIP": "Le fichier ZIP téléchargé ne contient pas 'memories_history.html'. Veuillez vérifier le fichier et réessayer.",
    "ERROR_INVALID_FILE_TYPE": "Type de fichier invalide. Veuillez télécharger votre fichier d'exportation .zip ou le fichier memories_history.html.",
    "UNZIPPING_FILE": "Extraction de votre fichier de souvenirs...",
    "ERROR_ZIP_CREATION": "Une erreur est survenue lors de la création du fichier ZIP.",
    "CREATING_ZIP": "Emballage de vos souvenirs...",
    "FINALIZING_ZIP": "Touche finale...",
    "PREPARING_DOWNLOAD": "Préparation...",
    "DOWNLOAD_HEADLINE_DEFAULT": "Téléchargement de vos souvenirs...",
    "DOWNLOAD_HEADLINE_YEAR": "🗓️ Récupération des souvenirs de {{selection}}",
    "DOWNLOAD_HEADLINE_COUNTRY": "🌍 Récupération des souvenirs de {{selection}}",
    "PROGRESS_COMPLETED": "✅ Terminé",
    "PROGRESS_PENDING": "⏳ En attente",
    "PROGRESS_FAILED": "❌ Échoué",
    "PROGRESS_TOTAL": "🔢 Total",
    "PROGRESS_PROCESSING_FILES": "⚙️ En cours...",
    "YEAR_SELECT_TITLE": "🗓️ Choisissez une année",
    "YEAR_TABLE_HEADER_YEAR": "📅 Année",
    "YEAR_TABLE_HEADER_PHOTOS": "🖼️ Photos",
    "YEAR_TABLE_HEADER_VIDEOS": "📹 Vidéos",
    "YEAR_TABLE_HEADER_TOTAL": "📦 Total",
    "MONTH_SELECT_TITLE": "🗓️ Sélectionnez les mois en {{year}}",
    "MONTH_TABLE_HEADER_MONTH": "📅 Mois",
    "BACK_TO_YEARS": "Retour aux années",
    "YEAR_SELECT_FOR_COUNTRY_TITLE": "🗓️ Sélectionnez les années en {{country}}",
    "BACK_TO_COUNTRIES": "Retour aux pays",
    "DOWNLOAD_HISTORY_NOTE": "Téléchargé : {{downloaded}}/{{total}}",
    "COUNTRY_SELECT_TITLE": "🌍 Choisissez un pays",
    "COUNTRY_TABLE_HEADER_COUNTRY": "🗺️ Pays",
    "COUNTRY_TABLE_HEADER_TOTAL": "🔢 Total",
    "COUNTRY_NO_LOCATIONS": "Aucun lieu trouvé.",
    "NO_LOCATION_DATA": "Aucune donnée de localisation",
    "LOCATION_NOT_IDENTIFIED": "Lieu mystérieux",
    "API_ERROR": "Erreur API",
    "LINKS_VALID_UNTIL": "Les liens sont valides jusqu'au {{date}}",
    "LINKS_EXPIRE_SOON": "Attention : Les liens expirent bientôt (le {{date}})",
    "LINKS_EXPIRED_ON": "Les liens ont expiré le {{date}}",
    "EXPIRED_LINKS_TITLE": "Les liens de téléchargement ont expiré",
    "EXPIRED_LINKS_DESCRIPTION": "Les liens de téléchargement de votre fichier <code>memories_history.html</code> ne sont valables que 7 jours après l'exportation de vos données depuis Snapchat. Pour continuer, vous devez demander une nouvelle exportation \"Mes données\" pour obtenir de nouveaux liens.",
    "STATUS_RETRYING": "⏳ Nouvelle tentative... (Tentative {{attempt}} sur {{max}})",
    "STATUS_EMBEDDING": "⏳ Intégration des métadonnées...",
    "STATUS_MERGING": "⏳ Fusion des images...",
    "STATUS_DOWNLOADING_OVERLAY": "⏳ Téléchargement de la surcouche...",
    "STATUS_DOWNLOADING": "⏳ Téléchargement...",
    "STATUS_COMPLETED": "✅ Terminé",
    "STATUS_FAILED": "❌ Échec du téléchargement",
    "STATUS_QUEUED": "🕒 En file d'attente pour téléchargement",
    "ZIP_FILENAME_PATTERN": "souvenirs-snapchat-{{mode}}-{{selection}}.zip",
    "ZIP_FILENAME_DEFAULT": "souvenirs-snapchat.zip",
    "LARGE_SELECTION_WARNING": "Cette grande sélection sera téléchargée en plusieurs fichiers ZIP plus petits pour plus de fiabilité.",
    "ZIP_FILENAME_PATTERN_BATCH": "souvenirs-snapchat-{{mode}}-{{selection}}-partie-{{current}}-sur-{{total}}.zip",
    "PROCESSING_PART": "📦 Traitement de la partie {{current}} sur {{total}}",
    "BATCH_CONTROL_TITLE": "Contrôle de téléchargement par lots",
    "BATCH_CONTROL_SUBTITLE": "Votre sélection a été divisée en {{count}} parties. Traitez-les individuellement ou toutes en même temps pour créer les fichiers ZIP téléchargeables.",
    "DOWNLOAD_ALL_BUTTON": "Télécharger tout ({{count}})",
    "PROCESS_ALL_BUTTON": "Traiter tout ({{count}})",
    "PART_STATUS_LABEL": "Partie {{current}} sur {{total}}",
    "DOWNLOAD_BUTTON": "Télécharger",
    "RETRY_BUTTON": "Réessayer",
    "PROCESS_BUTTON": "Traiter",
    "STATUS_LABEL_SUCCESS": "Succès",
    "STATUS_LABEL_FAILED": "Échec",
    "STATUS_LABEL_PROCESSING": "En cours...",
    "STATUS_LABEL_PLANNED": "Prêt à traiter",
    "REPORT_TITLE": "Snaploader Download Report",
    "REPORT_BATCH_INFO": "Batch {{batchNum}} of {{totalBatches}} &bull; Generated on {{date}}",
    "REPORT_STAT_TOTAL": "Total Files",
    "REPORT_STAT_SUCCESSFUL": "Successful",
    "REPORT_STAT_FAILED": "Failed",
    "REPORT_FAILED_MEMORIES_TITLE": "Failed Memories ({{count}})",
    "REPORT_FAILED_MEMORIES_SUBTITLE": "These files could not be downloaded or processed. You may need to request a new data export from Snapchat if the links have expired.",
    "REPORT_FOOTER_TEXT": "Generated by Snaploader &bull; ",
    "REPORT_FOOTER_LINK": "Create your own ZIP",
    "PENDING_GEOCODING": "En attente...",
    "COUNTRY_UNKNOWN": "Inconnu",
    "MONTH_JANUARY": "Janvier",
    "MONTH_FEBRUARY": "Février",
    "MONTH_MARCH": "Mars",
    "MONTH_APRIL": "Avril",
    "MONTH_MAY": "Mai",
    "MONTH_JUNE": "Juin",
    "MONTH_JULY": "Juillet",
    "MONTH_AUGUST": "Août",
    "MONTH_SEPTEMBER": "Septembre",
    "MONTH_OCTOBER": "Octobre",
    "MONTH_NOVEMBER": "Novembre",
    "MONTH_DECEMBER": "Décembre",
    "Afghanistan": "Afghanistan",
    "Angola": "Angola",
    "Albania": "Albanie",
    "United Arab Emirates": "Émirats arabes unis",
    "Argentina": "Argentine",
    "Armenia": "Arménie",
    "Antarctica": "Antarctique",
    "French Southern and Antarctic Lands": "Terres australes et antarctiques françaises",
    "Australia": "Australie",
    "Austria": "Autriche",
    "Azerbaijan": "Azerbaïdjan",
    "Burundi": "Burundi",
    "Belgium": "Belgique",
    "Benin": "Bénin",
    "Burkina Faso": "Burkina Faso",
    "Bangladesh": "Bangladesh",
    "Bulgaria": "Bulgarie",
    "The Bahamas": "Les Bahamas",
    "Bosnia and Herzegovina": "Bosnie-Herzégovine",
    "Belarus": "Biélorussie",
    "Belize": "Belize",
    "Bermuda": "Bermudes",
    "Bolivia": "Bolivie",
    "Brazil": "Brésil",
    "Brunei": "Brunei",
    "Bhutan": "Bhoutan",
    "Botswana": "Botswana",
    "Central African Republic": "République centrafricaine",
    "Canada": "Canada",
    "Switzerland": "Suisse",
    "Chile": "Chili",
    "China": "Chine",
    "Ivory Coast": "Côte d'Ivoire",
    "Cameroon": "Cameroun",
    "Democratic Republic of the Congo": "République démocratique du Congo",
    "Republic of the Congo": "République du Congo",
    "Colombia": "Colombie",
    "Costa Rica": "Costa Rica",
    "Cuba": "Cuba",
    "Northern Cyprus": "Chypre du Nord",
    "Cyprus": "Chypre",
    "Czechia": "Tchéquie",
    "Germany": "Allemagne",
    "Djibouti": "Djibouti",
    "Denmark": "Danemark",
    "Dominican Republic": "République dominicaine",
    "Algeria": "Algérie",
    "Ecuador": "Équateur",
    "Egypt": "Égypte",
    "Eritrea": "Érythrée",
    "Spain": "Espagne",
    "Estonia": "Estonie",
    "Ethiopia": "Éthiopie",
    "Finland": "Finlande",
    "Fiji": "Fidji",
    "Falkland Islands": "Îles Malouines",
    "France": "France",
    "Gabon": "Gabon",
    "United Kingdom": "Royaume-Uni",
    "Georgia": "Géorgie",
    "Ghana": "Ghana",
    "Guinea": "Guinée",
    "Gambia": "Gambie",
    "Guinea-Bissau": "Guinée-Bissau",
    "Equatorial Guinea": "Guinée équatoriale",
    "Greece": "Grèce",
    "Greenland": "Groenland",
    "Guatemala": "Guatemala",
    "Guyana": "Guyana",
    "Honduras": "Honduras",
    "Croatia": "Croatie",
    "Haiti": "Haïti",
    "Hungary": "Hongrie",
    "Indonesia": "Indonésie",
    "India": "Inde",
    "Ireland": "Irlande",
    "Iran": "Iran",
    "Iraq": "Irak",
    "Iceland": "Islande",
    "Israel": "Israël",
    "Italy": "Italie",
    "Jamaica": "Jamaïque",
    "Jordan": "Jordanie",
    "Japan": "Japon",
    "Kazakhstan": "Kazakhstan",
    "Kenya": "Kenya",
    "Kyrgyzstan": "Kirghizistan",
    "Cambodia": "Cambodge",
    "South Korea": "Corée du Sud",
    "Kosovo": "Kosovo",
    "Kuwait": "Koweït",
    "Laos": "Laos",
    "Lebanon": "Liban",
    "Liberia": "Libéria",
    "Libya": "Libye",
    "Sri Lanka": "Sri Lanka",
    "Lesotho": "Lesotho",
    "Lithuania": "Lituanie",
    "Luxembourg": "Luxembourg",
    "Latvia": "Lettonie",
    "Morocco": "Maroc",
    "Moldova": "Moldavie",
    "Madagascar": "Madagascar",
    "Mexico": "Mexique",
    "Macedonia": "Macédoine",
    "Mali": "Mali",
    "Myanmar": "Myanmar",
    "Montenegro": "Monténégro",
    "Mongolia": "Mongolie",
    "Mozambique": "Mozambique",
    "Mauritania": "Mauritanie",
    "Malawi": "Malawi",
    "Malaysia": "Malaisie",
    "Namibia": "Namibie",
    "New Caledonia": "Nouvelle-Calédonie",
    "Niger": "Niger",
    "Nigeria": "Nigéria",
    "Nicaragua": "Nicaragua",
    "Netherlands": "Pays-Bas",
    "Norway": "Norvège",
    "Nepal": "Népal",
    "New Zealand": "Nouvelle-Zélande",
    "Oman": "Oman",
    "Pakistan": "Pakistan",
    "Panama": "Panama",
    "Peru": "Pérou",
    "Philippines": "Philippines",
    "Papua New Guinea": "Papouasie-Nouvelle-Guinée",
    "Poland": "Pologne",
    "Puerto Rico": "Porto Rico",
    "North Korea": "Corée du Nord",
    "Portugal": "Portugal",
    "Paraguay": "Paraguay",
    "Qatar": "Qatar",
    "Romania": "Roumanie",
    "Russia": "Russie",
    "Rwanda": "Rwanda",
    "Western Sahara": "Sahara occidental",
    "Saudi Arabia": "Arabie saoudite",
    "Sudan": "Soudan",
    "South Sudan": "Soudan du Sud",
    "Senegal": "Sénégal",
    "Solomon Islands": "Îles Salomon",
    "Sierra Leone": "Sierra Leone",
    "El Salvador": "El Salvador",
    "Somaliland": "Somaliland",
    "Somalia": "Somalie",
    "Republic of Serbia": "République de Serbie",
    "Suriname": "Suriname",
    "Slovakia": "Slovaquie",
    "Slovenia": "Slovénie",
    "Sweden": "Suède",
    "Swaziland": "Swaziland",
    "Syria": "Syrie",
    "Chad": "Tchad",
    "Togo": "Togo",
    "Thailand": "Thaïlande",
    "Tajikistan": "Tadjikistan",
    "Turkmenistan": "Turkménistan",
    "East Timor": "Timor oriental",
    "Trinidad and Tobago": "Trinité-et-Tobago",
    "Tunisia": "Tunisie",
    "Turkey": "Turquie",
    "Taiwan": "Taïwan",
    "Tanzania": "Tanzanie",
    "Uganda": "Ouganda",
    "Ukraine": "Ukraine",
    "Uruguay": "Uruguay",
    "United States of America": "États-Unis d'Amérique",
    "Uzbekistan": "Ouzbékistan",
    "Venezuela": "Venezuela",
    "Vietnam": "Viêt Nam",
    "Vanuatu": "Vanuatu",
    "West Bank": "Cisjordanie",
    "Yemen": "Yémen",
    "South Africa": "Afrique du Sud",
    "Zambia": "Zambie",
    "Zimbabwe": "Zimbabwe"
  },
  es: {
    "APP_TITLE": "Snaploader",
    "HEADER_TITLE_PART_1": "Snap",
    "HEADER_TITLE_PART_2": "Loader",
    "HEADER_SUBTITLE": "Tus recuerdos, desbloqueados. 🔓",
    "FILE_UPLOAD_TITLE": "Dale tu archivo al fantasma 👻",
    "FILE_UPLOAD_DESCRIPTION": "Arrastra tu archivo de exportación de Snapchat <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">.zip</code> o solo el archivo <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">memories_history.html</code> para empezar. ✨",
    "FILE_UPLOAD_HELP_LINK": "❓ ¿Cómo obtengo este archivo?",
    "FILE_UPLOAD_BUTTON": "Seleccionar archivo",
    "UPLOAD_NEW_FILE_BUTTON": "Subir nuevo archivo",
    "PARSING_MESSAGE": "Leyendo tus recuerdos...",
    "PLEASE_WAIT": "Un momento...",
    "GEOCODING_MESSAGE": "Descubriendo dónde has estado... 🌍",
    "GEOCODING_REMAINING": "Restantes ⏳",
    "MEMORIES_TO_PROCESS": "recuerdos por procesar",
    "FOUND_LOCATIONS": "Lugares que has visitado 📍",
    "SEARCHING_FOR_LOCATIONS": "Buscando ubicaciones...",
    "CANCEL": "Cancelar",
    "CANCELLING_GEOCODING": "Deteniendo la búsqueda de ubicaciones...",
    "CANCELLING_DOWNLOAD": "Cancelando...",
    "BY_YEAR": "🗓️ Por año",
    "BY_COUNTRY": "🌍 Por país",
    "SELECTION_SUMMARY": "Estás descargando <span class=\"font-bold text-snap-yellow\">{{count}}</span> recuerdos (<span class=\"font-semibold text-white\">{{photos}}</span> fotos, <span class=\"font-semibold text-white\">{{videos}}</span> vídeos).",
    "START_DOWNLOAD": "¡Vamos! 🚀",
    "TOTAL_MEMORIES": "📚 Total de recuerdos",
    "PHOTOS": "🖼️ Fotos",
    "VIDEOS": "📹 Vídeos",
    "COMPLETE_TITLE": "¡Todo listo! 🎉",
    "COMPLETE_SUBTITLE": "Tus recuerdos están empaquetados en <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">{{filename}}</code> y listos para descargar.",
    "COMPLETE_DOWNLOAD_BUTTON": "💾 Descargar ZIP",
    "COMPLETE_START_OVER_BUTTON": "🔄 Empezar de nuevo",
    "ERROR_TITLE": "Oh, no... 😟",
    "ERROR_RETRY_BUTTON": "🔄 Intentar de nuevo",
    "ERROR_NO_MEMORIES_FOUND": "No se encontraron recuerdos en el archivo seleccionado. Por favor, comprueba el archivo e inténtalo de nuevo.",
    "ERROR_INVALID_FILE": "Error al procesar el archivo. Asegúrate de que es un archivo memories_history.html válido o un ZIP de exportación de datos de Snapchat válido.",
    "ERROR_NO_HTML_IN_ZIP": "El archivo ZIP subido no contiene 'memories_history.html'. Por favor, comprueba el archivo e inténtalo de nuevo.",
    "ERROR_INVALID_FILE_TYPE": "Tipo de archivo no válido. Sube tu archivo de exportación .zip o el archivo memories_history.html.",
    "UNZIPPING_FILE": "Extrayendo tu archivo de recuerdos...",
    "ERROR_ZIP_CREATION": "Ocurrió un error al crear el archivo ZIP.",
    "CREATING_ZIP": "Empaquetando tus recuerdos...",
    "FINALIZING_ZIP": "Dando los últimos toques...",
    "PREPARING_DOWNLOAD": "Preparando...",
    "DOWNLOAD_HEADLINE_DEFAULT": "Descargando tus recuerdos...",
    "DOWNLOAD_HEADLINE_YEAR": "🗓️ Descargando recuerdos de {{selection}}",
    "DOWNLOAD_HEADLINE_COUNTRY": "🌍 Descargando recuerdos de {{selection}}",
    "PROGRESS_COMPLETED": "✅ Hecho",
    "PROGRESS_PENDING": "⏳ Esperando",
    "PROGRESS_FAILED": "❌ Falló",
    "PROGRESS_TOTAL": "🔢 Total",
    "PROGRESS_PROCESSING_FILES": "⚙️ Trabajando...",
    "YEAR_SELECT_TITLE": "🗓️ Elige un año",
    "YEAR_TABLE_HEADER_YEAR": "📅 Año",
    "YEAR_TABLE_HEADER_PHOTOS": "🖼️ Fotos",
    "YEAR_TABLE_HEADER_VIDEOS": "📹 Vídeos",
    "YEAR_TABLE_HEADER_TOTAL": "📦 Total",
    "MONTH_SELECT_TITLE": "🗓️ Selecciona los meses en {{year}}",
    "MONTH_TABLE_HEADER_MONTH": "📅 Mes",
    "BACK_TO_YEARS": "Volver a los años",
    "YEAR_SELECT_FOR_COUNTRY_TITLE": "🗓️ Selecciona los años en {{country}}",
    "BACK_TO_COUNTRIES": "Volver a los países",
    "DOWNLOAD_HISTORY_NOTE": "Descargado: {{downloaded}}/{{total}}",
    "COUNTRY_SELECT_TITLE": "🌍 Elige un país",
    "COUNTRY_TABLE_HEADER_COUNTRY": "🗺️ País",
    "COUNTRY_TABLE_HEADER_TOTAL": "🔢 Total",
    "COUNTRY_NO_LOCATIONS": "No se encontraron ubicaciones.",
    "NO_LOCATION_DATA": "Sin datos de ubicación",
    "LOCATION_NOT_IDENTIFIED": "Ubicación misteriosa",
    "API_ERROR": "Error de API",
    "LINKS_VALID_UNTIL": "Los enlaces son válidos hasta el {{date}}",
    "LINKS_EXPIRE_SOON": "Advertencia: Los enlaces expiran pronto (el {{date}})",
    "LINKS_EXPIRED_ON": "Los enlaces expiraron el {{date}}",
    "EXPIRED_LINKS_TITLE": "Los enlaces de descarga han caducado",
    "EXPIRED_LINKS_DESCRIPTION": "Los enlaces de descarga de tu archivo <code>memories_history.html</code> solo son válidos durante 7 días después de exportar tus datos de Snapchat. Para continuar, debes solicitar una nueva exportación de \"Mis datos\" para obtener enlaces nuevos.",
    "STATUS_RETRYING": "⏳ Reintentando... (Intento {{attempt}} de {{max}})",
    "STATUS_EMBEDDING": "⏳ Incrustando metadatos...",
    "STATUS_MERGING": "⏳ Fusionando imágenes...",
    "STATUS_DOWNLOADING_OVERLAY": "⏳ Descargando superposición...",
    "STATUS_DOWNLOADING": "⏳ Descargando...",
    "STATUS_COMPLETED": "✅ Completado",
    "STATUS_FAILED": "❌ Falló la descarga",
    "STATUS_QUEUED": "🕒 En cola para descargar",
    "ZIP_FILENAME_PATTERN": "recuerdos-snapchat-{{mode}}-{{selection}}.zip",
    "ZIP_FILENAME_DEFAULT": "recuerdos-snapchat.zip",
    "LARGE_SELECTION_WARNING": "Esta gran selección se descargará como varios archivos ZIP más pequeños para mayor fiabilidad.",
    "ZIP_FILENAME_PATTERN_BATCH": "recuerdos-snapchat-{{mode}}-{{selection}}-parte-{{current}}-de-{{total}}.zip",
    "PROCESSING_PART": "📦 Procesando Parte {{current}} de {{total}}",
    "BATCH_CONTROL_TITLE": "Control de descarga por lotes",
    "BATCH_CONTROL_SUBTITLE": "Tu selección ha sido dividida en {{count}} partes. Procésalas individualmente o todas a la vez para crear los archivos ZIP descargables.",
    "DOWNLOAD_ALL_BUTTON": "Descargar todo ({{count}})",
    "PROCESS_ALL_BUTTON": "Procesar todo ({{count}})",
    "PART_STATUS_LABEL": "Parte {{current}} de {{total}}",
    "DOWNLOAD_BUTTON": "Descargar",
    "RETRY_BUTTON": "Reintentar",
    "PROCESS_BUTTON": "Procesar",
    "STATUS_LABEL_SUCCESS": "Éxito",
    "STATUS_LABEL_FAILED": "Fallido",
    "STATUS_LABEL_PROCESSING": "Procesando...",
    "STATUS_LABEL_PLANNED": "Listo para procesar",
    "REPORT_TITLE": "Snaploader Download Report",
    "REPORT_BATCH_INFO": "Batch {{batchNum}} of {{totalBatches}} &bull; Generated on {{date}}",
    "REPORT_STAT_TOTAL": "Total Files",
    "REPORT_STAT_SUCCESSFUL": "Successful",
    "REPORT_STAT_FAILED": "Failed",
    "REPORT_FAILED_MEMORIES_TITLE": "Failed Memories ({{count}})",
    "REPORT_FAILED_MEMORIES_SUBTITLE": "These files could not be downloaded or processed. You may need to request a new data export from Snapchat if the links have expired.",
    "REPORT_FOOTER_TEXT": "Generated by Snaploader &bull; ",
    "REPORT_FOOTER_LINK": "Create your own ZIP",
    "PENDING_GEOCODING": "Pendiente...",
    "COUNTRY_UNKNOWN": "Desconocido",
    "MONTH_JANUARY": "Enero",
    "MONTH_FEBRUARY": "Febrero",
    "MONTH_MARCH": "Marzo",
    "MONTH_APRIL": "Abril",
    "MONTH_MAY": "Mayo",
    "MONTH_JUNE": "Junio",
    "MONTH_JULY": "Julio",
    "MONTH_AUGUST": "Agosto",
    "MONTH_SEPTEMBER": "Septiembre",
    "MONTH_OCTOBER": "Octubre",
    "MONTH_NOVEMBER": "Noviembre",
    "MONTH_DECEMBER": "Diciembre",
    "Afghanistan": "Afganistán",
    "Angola": "Angola",
    "Albania": "Albania",
    "United Arab Emirates": "Emiratos Árabes Unidos",
    "Argentina": "Argentina",
    "Armenia": "Armenia",
    "Antarctica": "Antártida",
    "French Southern and Antarctic Lands": "Tierras Australes y Antárticas Francesas",
    "Australia": "Australia",
    "Austria": "Austria",
    "Azerbaijan": "Azerbaiyán",
    "Burundi": "Burundi",
    "Belgium": "Bélgica",
    "Benin": "Benín",
    "Burkina Faso": "Burkina Faso",
    "Bangladesh": "Bangladés",
    "Bulgaria": "Bulgaria",
    "The Bahamas": "Las Bahamas",
    "Bosnia and Herzegovina": "Bosnia y Herzegovina",
    "Belarus": "Bielorrusia",
    "Belize": "Belice",
    "Bermuda": "Bermudas",
    "Bolivia": "Bolivia",
    "Brazil": "Brasil",
    "Brunei": "Brunéi",
    "Bhutan": "Bután",
    "Botswana": "Botsuana",
    "Central African Republic": "República Centroafricana",
    "Canada": "Canadá",
    "Switzerland": "Suiza",
    "Chile": "Chile",
    "China": "China",
    "Ivory Coast": "Costa de Marfil",
    "Cameroon": "Camerún",
    "Democratic Republic of the Congo": "República Democrática del Congo",
    "Republic of the Congo": "República del Congo",
    "Colombia": "Colombia",
    "Costa Rica": "Costa Rica",
    "Cuba": "Cuba",
    "Northern Cyprus": "Norte de Chipre",
    "Cyprus": "Chipre",
    "Czechia": "Chequia",
    "Germany": "Alemania",
    "Djibouti": "Yibuti",
    "Denmark": "Dinamarca",
    "Dominican Republic": "República Dominicana",
    "Algeria": "Argelia",
    "Ecuador": "Ecuador",
    "Egypt": "Egipto",
    "Eritrea": "Eritrea",
    "Spain": "España",
    "Estonia": "Estonia",
    "Ethiopia": "Etiopía",
    "Finland": "Finlandia",
    "Fiji": "Fiyi",
    "Falkland Islands": "Islas Malvinas",
    "France": "Francia",
    "Gabon": "Gabón",
    "United Kingdom": "Reino Unido",
    "Georgia": "Georgia",
    "Ghana": "Ghana",
    "Guinea": "Guinea",
    "Gambia": "Gambia",
    "Guinea-Bissau": "Guinea-Bisáu",
    "Equatorial Guinea": "Guinea Ecuatorial",
    "Greece": "Grecia",
    "Greenland": "Groenlandia",
    "Guatemala": "Guatemala",
    "Guyana": "Guyana",
    "Honduras": "Honduras",
    "Croatia": "Croacia",
    "Haiti": "Haití",
    "Hungary": "Hungría",
    "Indonesia": "Indonesia",
    "India": "India",
    "Ireland": "Irlanda",
    "Iran": "Irán",
    "Iraq": "Irak",
    "Iceland": "Islandia",
    "Israel": "Israel",
    "Italy": "Italia",
    "Jamaica": "Jamaica",
    "Jordan": "Jordania",
    "Japan": "Japón",
    "Kazakhstan": "Kazajistán",
    "Kenya": "Kenia",
    "Kyrgyzstan": "Kirguistán",
    "Cambodia": "Camboya",
    "South Korea": "Corea del Sur",
    "Kosovo": "Kosovo",
    "Kuwait": "Kuwait",
    "Laos": "Laos",
    "Lebanon": "Líbano",
    "Liberia": "Liberia",
    "Libya": "Libia",
    "Sri Lanka": "Sri Lanka",
    "Lesotho": "Lesoto",
    "Lithuania": "Lituania",
    "Luxembourg": "Luxemburgo",
    "Latvia": "Letonia",
    "Morocco": "Marruecos",
    "Moldova": "Moldavia",
    "Madagascar": "Madagascar",
    "Mexico": "México",
    "Macedonia": "Macedonia",
    "Mali": "Malí",
    "Myanmar": "Myanmar",
    "Montenegro": "Montenegro",
    "Mongolia": "Mongolia",
    "Mozambique": "Mozambique",
    "Mauritania": "Mauritania",
    "Malawi": "Malaui",
    "Malaysia": "Malasia",
    "Namibia": "Namibia",
    "New Caledonia": "Nueva Caledonia",
    "Niger": "Níger",
    "Nigeria": "Nigeria",
    "Nicaragua": "Nicaragua",
    "Netherlands": "Países Bajos",
    "Norway": "Noruega",
    "Nepal": "Nepal",
    "New Zealand": "Nueva Zelanda",
    "Oman": "Omán",
    "Pakistan": "Pakistán",
    "Panama": "Panamá",
    "Peru": "Perú",
    "Philippines": "Filipinas",
    "Papua New Guinea": "Papúa Nueva Guinea",
    "Poland": "Polonia",
    "Puerto Rico": "Puerto Rico",
    "North Korea": "Corea del Norte",
    "Portugal": "Portugal",
    "Paraguay": "Paraguay",
    "Qatar": "Catar",
    "Romania": "Rumania",
    "Russia": "Rusia",
    "Rwanda": "Ruanda",
    "Western Sahara": "Sáhara Occidental",
    "Saudi Arabia": "Arabia Saudita",
    "Sudan": "Sudán",
    "South Sudan": "Sudán del Sur",
    "Senegal": "Senegal",
    "Solomon Islands": "Islas Salomón",
    "Sierra Leone": "Sierra Leona",
    "El Salvador": "El Salvador",
    "Somaliland": "Somalilandia",
    "Somalia": "Somalia",
    "Republic of Serbia": "República de Serbia",
    "Suriname": "Surinam",
    "Slovakia": "Eslovaquia",
    "Slovenia": "Eslovenia",
    "Sweden": "Suecia",
    "Swaziland": "Suazilandia",
    "Syria": "Siria",
    "Chad": "Chad",
    "Togo": "Togo",
    "Thailand": "Tailandia",
    "Tajikistan": "Tayikistán",
    "Turkmenistan": "Turkmenistán",
    "East Timor": "Timor Oriental",
    "Trinidad and Tobago": "Trinidad y Tobago",
    "Tunisia": "Túnez",
    "Turkey": "Turquía",
    "Taiwan": "Taiwán",
    "Tanzania": "Tanzania",
    "Uganda": "Uganda",
    "Ukraine": "Ucrania",
    "Uruguay": "Uruguay",
    "United States of America": "Estados Unidos de América",
    "Uzbekistan": "Uzbekistán",
    "Venezuela": "Venezuela",
    "Vietnam": "Vietnam",
    "Vanuatu": "Vanuatu",
    "West Bank": "Cisjordania",
    "Yemen": "Yemen",
    "South Africa": "Sudáfrica",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabue"
  },
  zh: {
    "APP_TITLE": "Snaploader",
    "HEADER_TITLE_PART_1": "Snap",
    "HEADER_TITLE_PART_2": "Loader",
    "HEADER_SUBTITLE": "你的回忆，解锁。🔓",
    "FILE_UPLOAD_TITLE": "把你的文件喂给小幽灵 👻",
    "FILE_UPLOAD_DESCRIPTION": "拖放你的 Snapchat 导出 <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">.zip</code> 文件或仅 <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">memories_history.html</code> 文件即可开始！✨",
    "FILE_UPLOAD_HELP_LINK": "❓ 如何获取此文件？",
    "FILE_UPLOAD_BUTTON": "选择文件",
    "UPLOAD_NEW_FILE_BUTTON": "上传新文件",
    "PARSING_MESSAGE": "正在读取你的回忆...",
    "PLEASE_WAIT": "请稍候...",
    "GEOCODING_MESSAGE": "正在探寻你的足迹... 🌍",
    "GEOCODING_REMAINING": "剩余 ⏳",
    "MEMORIES_TO_PROCESS": "个回忆待处理",
    "FOUND_LOCATIONS": "你曾去过的地方 📍",
    "SEARCHING_FOR_LOCATIONS": "正在搜索地点...",
    "CANCEL": "取消",
    "CANCELLING_GEOCODING": "正在停止地点搜索...",
    "CANCELLING_DOWNLOAD": "正在取消...",
    "BY_YEAR": "🗓️ 按年份",
    "BY_COUNTRY": "🌍 按国家",
    "SELECTION_SUMMARY": "你正在抓取 <span class=\"font-bold text-snap-yellow\">{{count}}</span> 个回忆（<span class=\"font-semibold text-white\">{{photos}}</span> 张照片，<span class=\"font-semibold text-white\">{{videos}}</span> 个视频）。",
    "START_DOWNLOAD": "开始吧！🚀",
    "TOTAL_MEMORIES": "📚 回忆总数",
    "PHOTOS": "🖼️ 照片",
    "VIDEOS": "📹 视频",
    "COMPLETE_TITLE": "全部完成！🎉",
    "COMPLETE_SUBTITLE": "你的回忆已打包在 <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">{{filename}}</code> 中，可以下载了！",
    "COMPLETE_DOWNLOAD_BUTTON": "💾 下载 ZIP",
    "COMPLETE_START_OVER_BUTTON": "🔄 重新开始",
    "ERROR_TITLE": "糟糕... 😟",
    "ERROR_RETRY_BUTTON": "🔄 重试",
    "ERROR_NO_MEMORIES_FOUND": "所选文件中未找到任何回忆。请检查文件并重试。",
    "ERROR_INVALID_FILE": "处理文件失败。请确保它是有效的 memories_history.html 文件或有效的 Snapchat 数据导出 ZIP 文件。",
    "ERROR_NO_HTML_IN_ZIP": "上传的 ZIP 文件不包含 'memories_history.html'。请检查文件并重试。",
    "ERROR_INVALID_FILE_TYPE": "文件类型无效。请上传你的 .zip 导出文件或 memories_history.html 文件。",
    "UNZIPPING_FILE": "正在提取你的回忆文件...",
    "ERROR_ZIP_CREATION": "创建 ZIP 文件时出错。",
    "CREATING_ZIP": "正在打包你的回忆...",
    "FINALIZING_ZIP": "正在完成最后步骤...",
    "PREPARING_DOWNLOAD": "准备中...",
    "DOWNLOAD_HEADLINE_DEFAULT": "正在下载你的回忆...",
    "DOWNLOAD_HEADLINE_YEAR": "🗓️ 正在抓取 {{selection}} 的回忆",
    "DOWNLOAD_HEADLINE_COUNTRY": "🌍 正在抓取来自 {{selection}} 的回忆",
    "PROGRESS_COMPLETED": "✅ 完成",
    "PROGRESS_PENDING": "⏳ 等待中",
    "PROGRESS_FAILED": "❌ 失败",
    "PROGRESS_TOTAL": "🔢 总计",
    "PROGRESS_PROCESSING_FILES": "⚙️ 处理中...",
    "YEAR_SELECT_TITLE": "🗓️ 选择年份",
    "YEAR_TABLE_HEADER_YEAR": "📅 年份",
    "YEAR_TABLE_HEADER_PHOTOS": "🖼️ 照片",
    "YEAR_TABLE_HEADER_VIDEOS": "📹 视频",
    "YEAR_TABLE_HEADER_TOTAL": "📦 总计",
    "MONTH_SELECT_TITLE": "🗓️ 在 {{year}} 中选择月份",
    "MONTH_TABLE_HEADER_MONTH": "📅 月份",
    "BACK_TO_YEARS": "返回年份",
    "YEAR_SELECT_FOR_COUNTRY_TITLE": "🗓️ 在 {{country}} 中选择年份",
    "BACK_TO_COUNTRIES": "返回国家",
    "DOWNLOAD_HISTORY_NOTE": "已下载: {{downloaded}}/{{total}}",
    "COUNTRY_SELECT_TITLE": "🌍 选择国家",
    "COUNTRY_TABLE_HEADER_COUNTRY": "🗺️ 国家",
    "COUNTRY_TABLE_HEADER_TOTAL": "🔢 总计",
    "COUNTRY_NO_LOCATIONS": "未找到任何地点。",
    "NO_LOCATION_DATA": "无位置数据",
    "LOCATION_NOT_IDENTIFIED": "神秘地点",
    "API_ERROR": "API 错误",
    "LINKS_VALID_UNTIL": "链接有效期至 {{date}}",
    "LINKS_EXPIRE_SOON": "警告：链接即将过期（于 {{date}}）",
    "LINKS_EXPIRED_ON": "链接已于 {{date}} 过期",
    "EXPIRED_LINKS_TITLE": "下载链接已过期",
    "EXPIRED_LINKS_DESCRIPTION": "您的 <code>memories_history.html</code> 文件中的下载链接仅在您从 Snapchat 导出数据后 7 天内有效。要继续，您必须请求新的“我的数据”导出来获取新的链接。",
    "STATUS_RETRYING": "⏳ 正在重试...（尝试次数 {{attempt}}/{{max}}）",
    "STATUS_EMBEDDING": "⏳ 正在嵌入元数据...",
    "STATUS_MERGING": "⏳ 正在合并图片...",
    "STATUS_DOWNLOADING_OVERLAY": "⏳ 正在下载叠加层...",
    "STATUS_DOWNLOADING": "⏳ 正在下载...",
    "STATUS_COMPLETED": "✅ 已完成",
    "STATUS_FAILED": "❌ 下载失败",
    "STATUS_QUEUED": "🕒 排队等待下载",
    "ZIP_FILENAME_PATTERN": "snapchat-回忆-{{mode}}-{{selection}}.zip",
    "ZIP_FILENAME_DEFAULT": "snapchat-回忆.zip",
    "LARGE_SELECTION_WARNING": "为了可靠性，这个大的选择将作为多个较小的ZIP文件下载。",
    "ZIP_FILENAME_PATTERN_BATCH": "snapchat-回忆-{{mode}}-{{selection}}-第-{{current}}-部分-共-{{total}}-部分.zip",
    "PROCESSING_PART": "📦 正在处理第 {{current}} 部分，共 {{total}} 部分",
    "BATCH_CONTROL_TITLE": "批量下载控制",
    "BATCH_CONTROL_SUBTITLE": "您的选择已被分成 {{count}} 个部分。单独处理或一次性处理它们以创建可下载的 ZIP 文件。",
    "DOWNLOAD_ALL_BUTTON": "全部下载 ({{count}})",
    "PROCESS_ALL_BUTTON": "全部处理 ({{count}})",
    "PART_STATUS_LABEL": "第 {{current}} 部分，共 {{total}} 部分",
    "DOWNLOAD_BUTTON": "下载",
    "RETRY_BUTTON": "重试",
    "PROCESS_BUTTON": "处理",
    "STATUS_LABEL_SUCCESS": "成功",
    "STATUS_LABEL_FAILED": "失败",
    "STATUS_LABEL_PROCESSING": "处理中...",
    "STATUS_LABEL_PLANNED": "准备处理",
    "REPORT_TITLE": "Snaploader Download Report",
    "REPORT_BATCH_INFO": "Batch {{batchNum}} of {{totalBatches}} &bull; Generated on {{date}}",
    "REPORT_STAT_TOTAL": "Total Files",
    "REPORT_STAT_SUCCESSFUL": "Successful",
    "REPORT_STAT_FAILED": "Failed",
    "REPORT_FAILED_MEMORIES_TITLE": "Failed Memories ({{count}})",
    "REPORT_FAILED_MEMORIES_SUBTITLE": "These files could not be downloaded or processed. You may need to request a new data export from Snapchat if the links have expired.",
    "REPORT_FOOTER_TEXT": "Generated by Snaploader &bull; ",
    "REPORT_FOOTER_LINK": "Create your own ZIP",
    "PENDING_GEOCODING": "待定...",
    "COUNTRY_UNKNOWN": "未知",
    "MONTH_JANUARY": "一月",
    "MONTH_FEBRUARY": "二月",
    "MONTH_MARCH": "三月",
    "MONTH_APRIL": "四月",
    "MONTH_MAY": "五月",
    "MONTH_JUNE": "六月",
    "MONTH_JULY": "七月",
    "MONTH_AUGUST": "八月",
    "MONTH_SEPTEMBER": "九月",
    "MONTH_OCTOBER": "十月",
    "MONTH_NOVEMBER": "十一月",
    "MONTH_DECEMBER": "十二月",
    "Afghanistan": "阿富汗",
    "Angola": "安哥拉",
    "Albania": "阿尔巴尼亚",
    "United Arab Emirates": "阿拉伯联合酋长国",
    "Argentina": "阿根廷",
    "Armenia": "亚美尼亚",
    "Antarctica": "南极洲",
    "French Southern and Antarctic Lands": "法属南部和南极领地",
    "Australia": "澳大利亚",
    "Austria": "奥地利",
    "Azerbaijan": "阿塞拜疆",
    "Burundi": "布隆迪",
    "Belgium": "比利时",
    "Benin": "贝宁",
    "Burkina Faso": "布基纳法索",
    "Bangladesh": "孟加拉国",
    "Bulgaria": "保加利亚",
    "The Bahamas": "巴哈马",
    "Bosnia and Herzegovina": "波斯尼亚和黑塞哥维那",
    "Belarus": "白俄罗斯",
    "Belize": "伯利兹",
    "Bermuda": "百慕大",
    "Bolivia": "玻利维亚",
    "Brazil": "巴西",
    "Brunei": "文莱",
    "Bhutan": "不丹",
    "Botswana": "博茨瓦纳",
    "Central African Republic": "中非共和国",
    "Canada": "加拿大",
    "Switzerland": "瑞士",
    "Chile": "智利",
    "China": "中国",
    "Ivory Coast": "科特迪瓦",
    "Cameroon": "喀麦隆",
    "Democratic Republic of the Congo": "刚果民主共和国",
    "Republic of the Congo": "刚果共和国",
    "Colombia": "哥伦比亚",
    "Costa Rica": "哥斯达黎加",
    "Cuba": "古巴",
    "Northern Cyprus": "北塞浦路斯",
    "Cyprus": "塞浦路斯",
    "Czechia": "捷克",
    "Germany": "德国",
    "Djibouti": "吉布提",
    "Denmark": "丹麦",
    "Dominican Republic": "多米尼加共和国",
    "Algeria": "阿尔及利亚",
    "Ecuador": "厄瓜多尔",
    "Egypt": "埃及",
    "Eritrea": "厄立特里亚",
    "Spain": "西班牙",
    "Estonia": "爱沙尼亚",
    "Ethiopia": "埃塞俄比亚",
    "Finland": "芬兰",
    "Fiji": "斐济",
    "Falkland Islands": "福克兰群岛",
    "France": "法国",
    "Gabon": "加蓬",
    "United Kingdom": "英国",
    "Georgia": "格鲁吉亚",
    "Ghana": "加纳",
    "Guinea": "几内亚",
    "Gambia": "冈比亚",
    "Guinea-Bissau": "几内亚比绍",
    "Equatorial Guinea": "赤道几内亚",
    "Greece": "希腊",
    "Greenland": "格陵兰",
    "Guatemala": "危地马拉",
    "Guyana": "圭亚那",
    "Honduras": "洪都拉斯",
    "Croatia": "克罗地亚",
    "Haiti": "海地",
    "Hungary": "匈牙利",
    "Indonesia": "印度尼西亚",
    "India": "印度",
    "Ireland": "爱尔兰",
    "Iran": "伊朗",
    "Iraq": "伊拉克",
    "Iceland": "冰岛",
    "Israel": "以色列",
    "Italy": "意大利",
    "Jamaica": "牙买加",
    "Jordan": "约旦",
    "Japan": "日本",
    "Kazakhstan": "哈萨克斯坦",
    "Kenya": "肯尼亚",
    "Kyrgyzstan": "吉尔吉斯斯坦",
    "Cambodia": "柬埔寨",
    "South Korea": "韩国",
    "Kosovo": "科索沃",
    "Kuwait": "科威特",
    "Laos": "老挝",
    "Lebanon": "黎巴嫩",
    "Liberia": "利比里亚",
    "Libya": "利比亚",
    "Sri Lanka": "斯里 Lanka",
    "Lesotho": "莱索托",
    "Lithuania": "立陶宛",
    "Luxembourg": "卢森堡",
    "Latvia": "拉脱维亚",
    "Morocco": "摩洛哥",
    "Moldova": "摩尔多瓦",
    "Madagascar": "马达加斯加",
    "Mexico": "墨西哥",
    "Macedonia": "马其顿",
    "Mali": "马里",
    "Myanmar": "缅甸",
    "Montenegro": "黑山",
    "Mongolia": "蒙古",
    "Mozambique": "莫桑比克",
    "Mauritania": "毛里塔尼亚",
    "Malawi": "马拉维",
    "Malaysia": "马来西亚",
    "Namibia": "纳米比亚",
    "New Caledonia": "新喀里多尼亚",
    "Niger": "尼日尔",
    "Nigeria": "尼日利亚",
    "Nicaragua": "尼加拉瓜",
    "Netherlands": "荷兰",
    "Norway": "挪威",
    "Nepal": "尼泊尔",
    "New Zealand": "新西兰",
    "Oman": "阿曼",
    "Pakistan": "巴基斯坦",
    "Panama": "巴拿马",
    "Peru": "秘鲁",
    "Philippines": "菲律宾",
    "Papua New Guinea": "巴布亚新几内亚",
    "Poland": "波兰",
    "Puerto Rico": "波多黎各",
    "North Korea": "朝鲜",
    "Portugal": "葡萄牙",
    "Paraguay": "巴拉圭",
    "Qatar": "卡塔尔",
    "Romania": "罗马尼亚",
    "Russia": "俄罗斯",
    "Rwanda": "卢旺达",
    "Western Sahara": "西撒哈拉",
    "Saudi Arabia": "沙特阿拉伯",
    "Sudan": "苏丹",
    "South Sudan": "南苏丹",
    "Senegal": "塞内加尔",
    "Solomon Islands": "所罗门群岛",
    "Sierra Leone": "塞拉利昂",
    "El Salvador": "萨尔瓦多",
    "Somaliland": "索马里兰",
    "Somalia": "索马里",
    "Republic of Serbia": "塞尔维亚共和国",
    "Suriname": "苏里南",
    "Slovakia": "斯洛伐克",
    "Slovenia": "斯洛文尼亚",
    "Sweden": "瑞典",
    "Swaziland": "斯威士兰",
    "Syria": "叙利亚",
    "Chad": "乍得",
    "Togo": "多哥",
    "Thailand": "泰国",
    "Tajikistan": "塔吉克斯坦",
    "Turkmenistan": "土库曼斯坦",
    "East Timor": "东帝汶",
    "Trinidad and Tobago": "特立尼达和多巴哥",
    "Tunisia": "突尼斯",
    "Turkey": "土耳其",
    "Taiwan": "台湾",
    "Tanzania": "坦桑尼亚",
    "Uganda": "乌干达",
    "Ukraine": "乌克兰",
    "Uruguay": "乌拉圭",
    "United States of America": "美利坚合众国",
    "Uzbekistan": "乌兹别克斯坦",
    "Venezuela": "委内瑞拉",
    "Vietnam": "越南",
    "Vanuatu": "瓦努阿图",
    "West Bank": "西岸",
    "Yemen": "也门",
    "South Africa": "南非",
    "Zambia": "赞比亚",
    "Zimbabwe": "津巴布韦"
  },
  hi: {
    "APP_TITLE": "Snaploader",
    "HEADER_TITLE_PART_1": "Snap",
    "HEADER_TITLE_PART_2": "Loader",
    "HEADER_SUBTITLE": "आपकी यादें, अनलॉक। 🔓",
    "FILE_UPLOAD_TITLE": "भूत को अपनी फ़ाइल खिलाओ 👻",
    "FILE_UPLOAD_DESCRIPTION": "शुरू करने के लिए अपनी Snapchat निर्यात <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">.zip</code> फ़ाइल या सिर्फ <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">memories_history.html</code> फ़ाइल डालें! ✨",
    "FILE_UPLOAD_HELP_LINK": "❓ मुझे यह फ़ाइल कैसे मिलेगी?",
    "FILE_UPLOAD_BUTTON": "फ़ाइल चुनें",
    "UPLOAD_NEW_FILE_BUTTON": "नई फ़ाइल अपलोड करें",
    "PARSING_MESSAGE": "आपकी यादें पढ़ रहा है...",
    "PLEASE_WAIT": "बस एक पल...",
    "GEOCODING_MESSAGE": "पता लगा रहा है कि आप कहाँ-कहाँ गए हैं... 🌍",
    "GEOCODING_REMAINING": "शेष ⏳",
    "MEMORIES_TO_PROCESS": "यादें संसाधित करने के लिए",
    "FOUND_LOCATIONS": "वे स्थान जहाँ आप गए हैं 📍",
    "SEARCHING_FOR_LOCATIONS": "स्थानों की खोज हो रही है...",
    "CANCEL": "रद्द करें",
    "CANCELLING_GEOCODING": "स्थान खोज रोक रहा है...",
    "CANCELLING_DOWNLOAD": "रद्द कर रहा है...",
    "BY_YEAR": "🗓️ वर्ष के अनुसार",
    "BY_COUNTRY": "🌍 देश के अनुसार",
    "SELECTION_SUMMARY": "आप <span class=\"font-bold text-snap-yellow\">{{count}}</span> यादें (<span class=\"font-semibold text-white\">{{photos}}</span> तस्वीरें, <span class=\"font-semibold text-white\">{{videos}}</span> वीडियो) प्राप्त कर रहे हैं।",
    "START_DOWNLOAD": "चलो चलें! 🚀",
    "TOTAL_MEMORIES": "📚 कुल यादें",
    "PHOTOS": "🖼️ तस्वीरें",
    "VIDEOS": "📹 वीडियो",
    "COMPLETE_TITLE": "सब हो गया! 🎉",
    "COMPLETE_SUBTITLE": "आपकी यादें <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">{{filename}}</code> में पैक हो गई हैं और जाने के लिए तैयार हैं!",
    "COMPLETE_DOWNLOAD_BUTTON": "💾 ज़िप डाउनलोड करें",
    "COMPLETE_START_OVER_BUTTON": "🔄 फिर से शुरू करें",
    "ERROR_TITLE": "ओह... 😟",
    "ERROR_RETRY_BUTTON": "🔄 फिर से प्रयास करें",
    "ERROR_NO_MEMORIES_FOUND": "चुनी गई फ़ाइल में कोई यादें नहीं मिलीं। कृपया फ़ाइल की जाँच करें और फिर से प्रयास करें।",
    "ERROR_INVALID_FILE": "फ़ाइल को संसाधित करने में विफल। कृपया सुनिश्चित करें कि यह एक वैध memories_history.html या एक वैध Snapchat डेटा निर्यात ज़िप है।",
    "ERROR_NO_HTML_IN_ZIP": "अपलोड की गई ज़िप फ़ाइल में 'memories_history.html' नहीं है। कृपया फ़ाइल की जाँच करें और फिर से प्रयास करें।",
    "ERROR_INVALID_FILE_TYPE": "अमान्य फ़ाइल प्रकार। कृपया अपनी .zip निर्यात फ़ाइल या memories_history.html फ़ाइल अपलोड करें।",
    "UNZIPPING_FILE": "आपकी यादों की फ़ाइल निकाली जा रही है...",
    "ERROR_ZIP_CREATION": "ज़िप फ़ाइल बनाते समय एक त्रुटि हुई।",
    "CREATING_ZIP": "आपकी यादें पैक कर रहा है...",
    "FINALIZING_ZIP": "अंतिम रूप दे रहा है...",
    "PREPARING_DOWNLOAD": "तैयारी हो रही है...",
    "DOWNLOAD_HEADLINE_DEFAULT": "आपकी यादें डाउनलोड हो रही हैं...",
    "DOWNLOAD_HEADLINE_YEAR": "🗓️ {{selection}} से यादें प्राप्त की जा रही हैं",
    "DOWNLOAD_HEADLINE_COUNTRY": "🌍 {{selection}} से यादें प्राप्त की जा रही हैं",
    "PROGRESS_COMPLETED": "✅ हो गया",
    "PROGRESS_PENDING": "⏳ प्रतीक्षा में",
    "PROGRESS_FAILED": "❌ विफल",
    "PROGRESS_TOTAL": "🔢 कुल",
    "PROGRESS_PROCESSING_FILES": "⚙️ काम चल रहा है...",
    "YEAR_SELECT_TITLE": "🗓️ एक वर्ष चुनें",
    "YEAR_TABLE_HEADER_YEAR": "📅 वर्ष",
    "YEAR_TABLE_HEADER_PHOTOS": "🖼️ तस्वीरें",
    "YEAR_TABLE_HEADER_VIDEOS": "📹 वीडियो",
    "YEAR_TABLE_HEADER_TOTAL": "📦 कुल",
    "MONTH_SELECT_TITLE": "🗓️ {{year}} में महीने चुनें",
    "MONTH_TABLE_HEADER_MONTH": "📅 महीना",
    "BACK_TO_YEARS": "वर्षों पर वापस जाएं",
    "YEAR_SELECT_FOR_COUNTRY_TITLE": "🗓️ {{country}} में वर्ष चुनें",
    "BACK_TO_COUNTRIES": "देशों पर वापस जाएं",
    "DOWNLOAD_HISTORY_NOTE": "डाउनलोड किया गया: {{downloaded}}/{{total}}",
    "COUNTRY_SELECT_TITLE": "🌍 एक देश चुनें",
    "COUNTRY_TABLE_HEADER_COUNTRY": "🗺️ देश",
    "COUNTRY_TABLE_HEADER_TOTAL": "🔢 कुल",
    "COUNTRY_NO_LOCATIONS": "कोई स्थान नहीं मिला।",
    "NO_LOCATION_DATA": "कोई स्थान डेटा नहीं",
    "LOCATION_NOT_IDENTIFIED": "रहस्यमय स्थान",
    "API_ERROR": "एपीआई त्रुटि",
    "LINKS_VALID_UNTIL": "लिंक {{date}} तक मान्य हैं",
    "LINKS_EXPIRE_SOON": "चेतावनी: लिंक जल्द ही समाप्त हो जाएंगे ({{date}} को)",
    "LINKS_EXPIRED_ON": "लिंक {{date}} को समाप्त हो गए",
    "EXPIRED_LINKS_TITLE": "डाउनलोड लिंक समाप्त हो गए हैं",
    "EXPIRED_LINKS_DESCRIPTION": "आपकी <code>memories_history.html</code> फ़ाइल में डाउनलोड लिंक Snapchat से अपना डेटा निर्यात करने के 7 दिनों के लिए ही मान्य होते हैं। जारी रखने के लिए, आपको नए लिंक प्राप्त करने के लिए एक नया \"मेरा डेटा\" निर्यात का अनुरोध करना होगा।",
    "STATUS_RETRYING": "⏳ पुनः प्रयास कर रहा है... (प्रयास {{attempt}} का {{max}})",
    "STATUS_EMBEDDING": "⏳ मेटाडेटा एम्बेड कर रहा है...",
    "STATUS_MERGING": "⏳ छवियाँ मिला रहा है...",
    "STATUS_DOWNLOADING_OVERLAY": "⏳ ओवरले डाउनलोड कर रहा है...",
    "STATUS_DOWNLOADING": "⏳ डाउनलोड हो रहा है...",
    "STATUS_COMPLETED": "✅ पूरा हुआ",
    "STATUS_FAILED": "❌ डाउनलोड विफल",
    "STATUS_QUEUED": "🕒 डाउनलोड के लिए कतार में",
    "ZIP_FILENAME_PATTERN": "snapchat-यादें-{{mode}}-{{selection}}.zip",
    "ZIP_FILENAME_DEFAULT": "snapchat-यादें.zip",
    "LARGE_SELECTION_WARNING": "विश्वसनीयता के लिए यह बड़ा चयन कई छोटी ज़िप फ़ाइलों के रूप में डाउनलोड किया जाएगा।",
    "ZIP_FILENAME_PATTERN_BATCH": "snapchat-यादें-{{mode}}-{{selection}}-भाग-{{current}}-का-{{total}}.zip",
    "PROCESSING_PART": "📦 भाग {{current}} का {{total}} संसाधित हो रहा है",
    "BATCH_CONTROL_TITLE": "बैच डाउनलोड नियंत्रण",
    "BATCH_CONTROL_SUBTITLE": "आपका चयन {{count}} भागों में विभाजित किया गया है। डाउनलोड करने योग्य ज़िप फ़ाइलें बनाने के लिए उन्हें व्यक्तिगत रूप से या एक साथ संसाधित करें।",
    "DOWNLOAD_ALL_BUTTON": "सभी डाउनलोड करें ({{count}})",
    "PROCESS_ALL_BUTTON": "सभी को संसाधित करें ({{count}})",
    "PART_STATUS_LABEL": "भाग {{current}} का {{total}}",
    "DOWNLOAD_BUTTON": "डाउनलोड करें",
    "RETRY_BUTTON": "पुनः प्रयास करें",
    "PROCESS_BUTTON": "संसाधित करें",
    "STATUS_LABEL_SUCCESS": "सफलता",
    "STATUS_LABEL_FAILED": "विफल",
    "STATUS_LABEL_PROCESSING": "संसाधित हो रहा है...",
    "STATUS_LABEL_PLANNED": "संसाधित करने के लिए तैयार",
    "REPORT_TITLE": "Snaploader Download Report",
    "REPORT_BATCH_INFO": "Batch {{batchNum}} of {{totalBatches}} &bull; Generated on {{date}}",
    "REPORT_STAT_TOTAL": "Total Files",
    "REPORT_STAT_SUCCESSFUL": "Successful",
    "REPORT_STAT_FAILED": "Failed",
    "REPORT_FAILED_MEMORIES_TITLE": "Failed Memories ({{count}})",
    "REPORT_FAILED_MEMORIES_SUBTITLE": "These files could not be downloaded or processed. You may need to request a new data export from Snapchat if the links have expired.",
    "REPORT_FOOTER_TEXT": "Generated by Snaploader &bull; ",
    "REPORT_FOOTER_LINK": "Create your own ZIP",
    "PENDING_GEOCODING": "लंबित...",
    "COUNTRY_UNKNOWN": "अज्ञात",
    "MONTH_JANUARY": "जनवरी",
    "MONTH_FEBRUARY": "फ़रवरी",
    "MONTH_MARCH": "मार्च",
    "MONTH_APRIL": "अप्रैल",
    "MONTH_MAY": "मई",
    "MONTH_JUNE": "जून",
    "MONTH_JULY": "जुलाई",
    "MONTH_AUGUST": "अगस्त",
    "MONTH_SEPTEMBER": "सितंबर",
    "MONTH_OCTOBER": "अक्टूबर",
    "MONTH_NOVEMBER": "नवंबर",
    "MONTH_DECEMBER": "दिसंबर",
    "Afghanistan": "अफ़गानिस्तान",
    "Angola": "अंगोला",
    "Albania": "अल्बानिया",
    "United Arab Emirates": "संयुक्त अरब अमीरात",
    "Argentina": "अर्जेंटीना",
    "Armenia": "आर्मेनिया",
    "Antarctica": "अंटार्कटिका",
    "French Southern and Antarctic Lands": "फ्रांसीसी दक्षिणी और अंटार्कटिक भूमि",
    "Australia": "ऑस्ट्रेलिया",
    "Austria": "ऑस्ट्रिया",
    "Azerbaijan": "अज़रबैजान",
    "Burundi": "बुरुंडी",
    "Belgium": "बेल्जियम",
    "Benin": "बेनिन",
    "Burkina Faso": "बुर्किना फासो",
    "Bangladesh": "बांग्लादेश",
    "Bulgaria": "बुल्गारिया",
    "The Bahamas": "बहामास",
    "Bosnia and Herzegovina": "बोस्निया और हर्जेगोविना",
    "Belarus": "बेलारूस",
    "Belize": "बेलीज",
    "Bermuda": "बरमूडा",
    "Bolivia": "बोलीविया",
    "Brazil": "ब्राज़िल",
    "Brunei": "ब्रुनेई",
    "Bhutan": "भूटान",
    "Botswana": "बोत्सवाना",
    "Central African Republic": "मध्य अफ़्रीकी गणराज्य",
    "Canada": "कनाडा",
    "Switzerland": "स्विट्ज़रलैंड",
    "Chile": "चिली",
    "China": "चीन",
    "Ivory Coast": "आइवरी कोस्ट",
    "Cameroon": "कैमरून",
    "Democratic Republic of the Congo": "कांगो लोकतांत्रिक गणराज्य",
    "Republic of the Congo": "कांगो गणराज्य",
    "Colombia": "कोलंबिया",
    "Costa Rica": "कोस्टा रिका",
    "Cuba": "क्यूबा",
    "Northern Cyprus": "उत्तरी साइप्रस",
    "Cyprus": "साइप्रस",
    "Czechia": "चेकिया",
    "Germany": "जर्मनी",
    "Djibouti": "जिबूती",
    "Denmark": "डेनमार्क",
    "Dominican Republic": "डोमिनिकन गणराज्य",
    "Algeria": "अल्जीरिया",
    "Ecuador": "इक्वाडोर",
    "Egypt": "मिस्र",
    "Eritrea": "इरिट्रिया",
    "Spain": "स्पेन",
    "Estonia": "एस्टोनिया",
    "Ethiopia": "इथियोपिया",
    "Finland": "फिनलैंड",
    "Fiji": "फ़िजी",
    "Falkland Islands": "फ़ॉकलैंड द्वीप समूह",
    "France": "फ्रांस",
    "Gabon": "गैबॉन",
    "United Kingdom": "यूनाइटेड किंगडम",
    "Georgia": "जॉर्जिया",
    "Ghana": "घाना",
    "Guinea": "गिनी",
    "Gambia": "गाम्बिया",
    "Guinea-Bissau": "गिनी-बिसाऊ",
    "Equatorial Guinea": "भूमध्यरेखीय गिनी",
    "Greece": "यूनान",
    "Greenland": "ग्रीनलैंड",
    "Guatemala": "ग्वाटेमाला",
    "Guyana": "गुयाना",
    "Honduras": "होंडुरास",
    "Croatia": "क्रोएशिया",
    "Haiti": "हैती",
    "Hungary": "हंगरी",
    "Indonesia": "इंडोनेशिया",
    "India": "भारत",
    "Ireland": "आयरलैंड",
    "Iran": "ईरान",
    "Iraq": "इराक",
    "Iceland": "आइसलैंड",
    "Israel": "इज़राइल",
    "Italy": "इटली",
    "Jamaica": "जमैका",
    "Jordan": "जॉर्डन",
    "Japan": "जापान",
    "Kazakhstan": "कजाकिस्तान",
    "Kenya": "केन्या",
    "Kyrgyzstan": "किर्गिज़स्तान",
    "Cambodia": "कंबोडिया",
    "South Korea": "दक्षिण कोरिया",
    "Kosovo": "कोसोवो",
    "Kuwait": "कुवैत",
    "Laos": "लाओस",
    "Lebanon": "लेबनान",
    "Liberia": "लाइबेरिया",
    "Libya": "लीबिया",
    "Sri Lanka": "श्रीलंका",
    "Lesotho": "लेसोथो",
    "Lithuania": "लिथुआनिया",
    "Luxembourg": "लक्ज़मबर्ग",
    "Latvia": "लातविया",
    "Morocco": "मोरक्को",
    "Moldova": "मोल्दोवा",
    "Madagascar": "मेडागास्कर",
    "Mexico": "मेक्सिको",
    "Macedonia": "मैसेडोनिया",
    "Mali": "माली",
    "Myanmar": "म्यांमार",
    "Montenegro": "मोंटेनेग्रो",
    "Mongolia": "मंगोलिया",
    "Mozambique": "मोज़ाम्बिक",
    "Mauritania": "मॉरिटानिया",
    "Malawi": "मलावी",
    "Malaysia": "मलेशिया",
    "Namibia": "नामीबिया",
    "New Caledonia": "न्यू कैलेडोनिया",
    "Niger": "नाइजर",
    "Nigeria": "नाइजीरिया",
    "Nicaragua": "निकारागुआ",
    "Netherlands": "नीदरलैंड",
    "Norway": "नॉर्वे",
    "Nepal": "नेपाल",
    "New Zealand": "न्यूज़ीलैंड",
    "Oman": "ओमान",
    "Pakistan": "पाकिस्तान",
    "Panama": "पनामा",
    "Peru": "पेरू",
    "Philippines": "फिलीपींस",
    "Papua New Guinea": "पापुआ न्यू गिनी",
    "Poland": "पोलैंड",
    "Puerto Rico": "प्यूर्टो रिको",
    "North Korea": "उत्तर कोरिया",
    "Portugal": "पुर्तगाल",
    "Paraguay": "पैराग्वे",
    "Qatar": "कतर",
    "Romania": "रोमानिया",
    "Russia": "रूस",
    "Rwanda": "रवांडा",
    "Western Sahara": "पश्चिमी सहारा",
    "Saudi Arabia": "सऊदी अरब",
    "Sudan": "सूडान",
    "South Sudan": "दक्षिण सूडान",
    "Senegal": "सेनेगल",
    "Solomon Islands": "सोलोमन द्वीप",
    "Sierra Leone": "सिएरा लियोन",
    "El Salvador": "अल साल्वाडोर",
    "Somaliland": "सोमालीलैंड",
    "Somalia": "सोमालिया",
    "Republic of Serbia": "सर्बिया गणराज्य",
    "Suriname": "सूरीनाम",
    "Slovakia": "स्लोवाकिया",
    "Slovenia": "स्लोवेनिया",
    "Sweden": "स्वीडन",
    "Swaziland": "स्वाज़ीलैंड",
    "Syria": "सीरिया",
    "Chad": "चाड",
    "Togo": "टोगो",
    "Thailand": "थाईलैंड",
    "Tajikistan": "ताजिकिस्तान",
    "Turkmenistan": "तुर्कमेनिस्तान",
    "East Timor": "पूर्वी तिमोर",
    "Trinidad and Tobago": "त्रिनिदाद और टोबैगो",
    "Tunisia": "ट्यूनीशिया",
    "Turkey": "तुर्की",
    "Taiwan": "ताइवान",
    "Tanzania": "तंजानिया",
    "Uganda": "युगांडा",
    "Ukraine": "यूक्रेन",
    "Uruguay": "उरुग्वे",
    "United States of America": "संयुक्त राज्य अमेरिका",
    "Uzbekistan": "उज़्बेकिस्तान",
    "Venezuela": "वेनेजुएला",
    "Vietnam": "वियतनाम",
    "Vanuatu": "वानुअतु",
    "West Bank": "वेस्ट बैंक",
    "Yemen": "यमन",
    "South Africa": "दक्षिण अफ्रीका",
    "Zambia": "जाम्बिया",
    "Zimbabwe": "ज़िम्बाब्वे"
  },
  bn: {
    "APP_TITLE": "Snaploader",
    "HEADER_TITLE_PART_1": "Snap",
    "HEADER_TITLE_PART_2": "Loader",
    "HEADER_SUBTITLE": "আপনার স্মৃতি, আনলক করা। 🔓",
    "FILE_UPLOAD_TITLE": "ভূতকে আপনার ফাইল খাওয়ান 👻",
    "FILE_UPLOAD_DESCRIPTION": "শুরু করতে আপনার Snapchat এক্সপোর্ট <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">.zip</code> ফাইল অথবা শুধু <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">memories_history.html</code> ফাইলটি এখানে ফেলুন! ✨",
    "FILE_UPLOAD_HELP_LINK": "❓ আমি এই ফাইলটি কিভাবে পাব?",
    "FILE_UPLOAD_BUTTON": "ফাইল নির্বাচন করুন",
    "UPLOAD_NEW_FILE_BUTTON": "নতুন ফাইল আপলোড করুন",
    "PARSING_MESSAGE": "আপনার স্মৃতি পড়া হচ্ছে...",
    "PLEASE_WAIT": "একটু অপেক্ষা করুন...",
    "GEOCODING_MESSAGE": "আপনি কোথায় কোথায় ছিলেন তা খুঁজে বের করা হচ্ছে... 🌍",
    "GEOCODING_REMAINING": "বাকি আছে ⏳",
    "MEMORIES_TO_PROCESS": "স্মৃতি প্রক্রিয়া করার জন্য",
    "FOUND_LOCATIONS": "আপনি যে জায়গাগুলিতে গিয়েছেন 📍",
    "SEARCHING_FOR_LOCATIONS": "অবস্থান অনুসন্ধান করা হচ্ছে...",
    "CANCEL": "বাতিল করুন",
    "CANCELLING_GEOCODING": "অবস্থান অনুসন্ধান বন্ধ করা হচ্ছে...",
    "CANCELLING_DOWNLOAD": "বাতিল করা হচ্ছে...",
    "BY_YEAR": "🗓️ বছর অনুসারে",
    "BY_COUNTRY": "🌍 দেশ অনুসারে",
    "SELECTION_SUMMARY": "আপনি <span class=\"font-bold text-snap-yellow\">{{count}}</span>টি স্মৃতি (<span class=\"font-semibold text-white\">{{photos}}</span>টি ছবি, <span class=\"font-semibold text-white\">{{videos}}</span>টি ভিডিও) সংগ্রহ করছেন।",
    "START_DOWNLOAD": "চলো শুরু করি! 🚀",
    "TOTAL_MEMORIES": "📚 মোট স্মৃতি",
    "PHOTOS": "🖼️ ছবি",
    "VIDEOS": "📹 ভিডিও",
    "COMPLETE_TITLE": "সব শেষ! 🎉",
    "COMPLETE_SUBTITLE": "আপনার স্মৃতিগুলি <code class=\"bg-snap-dark text-snap-yellow rounded px-1.5 py-1 text-sm\">{{filename}}</code> ফাইলে প্যাক করা হয়েছে এবং ডাউনলোডের জন্য প্রস্তুত!",
    "COMPLETE_DOWNLOAD_BUTTON": "💾 জিপ ডাউনলোড করুন",
    "COMPLETE_START_OVER_BUTTON": "🔄 আবার শুরু করুন",
    "ERROR_TITLE": "ওহ... 😟",
    "ERROR_RETRY_BUTTON": "🔄 আবার চেষ্টা করুন",
    "ERROR_NO_MEMORIES_FOUND": "নির্বাচিত ফাইলে কোনো স্মৃতি পাওয়া যায়নি। অনুগ্রহ করে ফাইলটি পরীক্ষা করে আবার চেষ্টা করুন।",
    "ERROR_INVALID_FILE": "ফাইল প্রক্রিয়া করতে ব্যর্থ। অনুগ্রহ করে নিশ্চিত করুন যে এটি একটি বৈধ memories_history.html বা একটি বৈধ Snapchat ডেটা এক্সপোর্ট জিপ।",
    "ERROR_NO_HTML_IN_ZIP": "আপলোড করা জিপ ফাইলে 'memories_history.html' নেই। অনুগ্রহ করে ফাইলটি পরীক্ষা করে আবার চেষ্টা করুন।",
    "ERROR_INVALID_FILE_TYPE": "অবৈধ ফাইলের প্রকার। অনুগ্রহ করে আপনার .zip এক্সপোর্ট ফাইল বা memories_history.html ফাইলটি আপলোড করুন।",
    "UNZIPPING_FILE": "আপনার স্মৃতির ফাইলটি এক্সট্রাক্ট করা হচ্ছে...",
    "ERROR_ZIP_CREATION": "জিপ ফাইল তৈরি করার সময় একটি ত্রুটি ঘটেছে।",
    "CREATING_ZIP": "আপনার স্মৃতি প্যাক করা হচ্ছে...",
    "FINALIZING_ZIP": "শেষ মুহূর্তের ছোঁয়া...",
    "PREPARING_DOWNLOAD": "প্রস্তুত হচ্ছে...",
    "DOWNLOAD_HEADLINE_DEFAULT": "আপনার স্মৃতি ডাউনলোড করা হচ্ছে...",
    "DOWNLOAD_HEADLINE_YEAR": "🗓️ {{selection}} থেকে স্মৃতি সংগ্রহ করা হচ্ছে",
    "DOWNLOAD_HEADLINE_COUNTRY": "🌍 {{selection}} থেকে স্মৃতি সংগ্রহ করা হচ্ছে",
    "PROGRESS_COMPLETED": "✅ সম্পন্ন",
    "PROGRESS_PENDING": "⏳ অপেক্ষমান",
    "PROGRESS_FAILED": "❌ ব্যর্থ",
    "PROGRESS_TOTAL": "🔢 মোট",
    "PROGRESS_PROCESSING_FILES": "⚙️ কাজ চলছে...",
    "YEAR_SELECT_TITLE": "🗓️ একটি বছর নির্বাচন করুন",
    "YEAR_TABLE_HEADER_YEAR": "📅 বছর",
    "YEAR_TABLE_HEADER_PHOTOS": "🖼️ ছবি",
    "YEAR_TABLE_HEADER_VIDEOS": "📹 ভিডিও",
    "YEAR_TABLE_HEADER_TOTAL": "📦 মোট",
    "MONTH_SELECT_TITLE": "🗓️ {{year}} সালের মাস নির্বাচন করুন",
    "MONTH_TABLE_HEADER_MONTH": "📅 মাস",
    "BACK_TO_YEARS": "বছরগুলিতে ফিরে যান",
    "YEAR_SELECT_FOR_COUNTRY_TITLE": "🗓️ {{country}} এ বছর নির্বাচন করুন",
    "BACK_TO_COUNTRIES": "দেশগুলিতে ফিরে যান",
    "DOWNLOAD_HISTORY_NOTE": "ডাউনলোড হয়েছে: {{downloaded}}/{{total}}",
    "COUNTRY_SELECT_TITLE": "🌍 একটি দেশ নির্বাচন করুন",
    "COUNTRY_TABLE_HEADER_COUNTRY": "🗺️ দেশ",
    "COUNTRY_TABLE_HEADER_TOTAL": "🔢 মোট",
    "COUNTRY_NO_LOCATIONS": "কোনো অবস্থান পাওয়া যায়নি।",
    "NO_LOCATION_DATA": "কোনো অবস্থানের ডেটা নেই",
    "LOCATION_NOT_IDENTIFIED": "রহস্যময় অবস্থান",
    "API_ERROR": "এপিআই ত্রুটি",
    "LINKS_VALID_UNTIL": "লিঙ্কগুলি {{date}} পর্যন্ত বৈধ",
    "LINKS_EXPIRE_SOON": "সতর্কতা: লিঙ্কগুলির মেয়াদ শীঘ্রই শেষ হবে ({{date}} তারিখে)",
    "LINKS_EXPIRED_ON": "লিঙ্কগুলির মেয়াদ {{date}} তারিখে শেষ হয়ে গেছে",
    "EXPIRED_LINKS_TITLE": "ডাউনলোড লিঙ্কগুলির মেয়াদ শেষ হয়ে গেছে",
    "EXPIRED_LINKS_DESCRIPTION": "আপনার <code>memories_history.html</code> ফাইলের ডাউনলোড লিঙ্কগুলি Snapchat থেকে আপনার ডেটা এক্সপোর্ট করার পর মাত্র ৭ দিনের জন্য বৈধ থাকে। চালিয়ে যেতে, আপনাকে নতুন লিঙ্ক পেতে একটি নতুন \"আমার ডেটা\" এক্সপোর্টের অনুরোধ করতে হবে।",
    "STATUS_RETRYING": "⏳ পুনরায় চেষ্টা করা হচ্ছে... (চেষ্টা {{attempt}} এর {{max}})",
    "STATUS_EMBEDDING": "⏳ মেটাডেটা এমবেড করা হচ্ছে...",
    "STATUS_MERGING": "⏳ ছবি একত্রিত করা হচ্ছে...",
    "STATUS_DOWNLOADING_OVERLAY": "⏳ ওভারলে ডাউনলোড করা হচ্ছে...",
    "STATUS_DOWNLOADING": "⏳ ডাউনলোড হচ্ছে...",
    "STATUS_COMPLETED": "✅ সম্পন্ন হয়েছে",
    "STATUS_FAILED": "❌ ডাউনলোড ব্যর্থ হয়েছে",
    "STATUS_QUEUED": "🕒 ডাউনলোডের জন্য সারিবদ্ধ",
    "ZIP_FILENAME_PATTERN": "snapchat-স্মৃতি-{{mode}}-{{selection}}.zip",
    "ZIP_FILENAME_DEFAULT": "snapchat-স্মৃতি.zip",
    "LARGE_SELECTION_WARNING": "নির্ভরযোগ্যতার জন্য এই বড় নির্বাচনটি একাধিক ছোট জিপ ফাইল হিসাবে ডাউনলোড করা হবে।",
    "ZIP_FILENAME_PATTERN_BATCH": "snapchat-স্মৃতি-{{mode}}-{{selection}}-অংশ-{{current}}-এর-{{total}}.zip",
    "PROCESSING_PART": "📦 অংশ {{current}} এর {{total}} প্রক্রিয়া করা হচ্ছে",
    "BATCH_CONTROL_TITLE": "ব্যাচ ডাউনলোড নিয়ন্ত্রণ",
    "BATCH_CONTROL_SUBTITLE": "আপনার নির্বাচন {{count}}টি অংশে বিভক্ত করা হয়েছে। ডাউনলোডযোগ্য জিপ ফাইল তৈরি করতে এগুলি পৃথকভাবে বা একসাথে প্রক্রিয়া করুন।",
    "DOWNLOAD_ALL_BUTTON": "সব ডাউনলোড করুন ({{count}})",
    "PROCESS_ALL_BUTTON": "সব প্রক্রিয়া করুন ({{count}})",
    "PART_STATUS_LABEL": "অংশ {{current}} এর {{total}}",
    "DOWNLOAD_BUTTON": "ডাউনলোড করুন",
    "RETRY_BUTTON": "পুনরায় চেষ্টা করুন",
    "PROCESS_BUTTON": "প্রক্রিয়া করুন",
    "STATUS_LABEL_SUCCESS": "সফল",
    "STATUS_LABEL_FAILED": "ব্যর্থ",
    "STATUS_LABEL_PROCESSING": "প্রক্রিয়াকরণ...",
    "STATUS_LABEL_PLANNED": "প্রক্রিয়া করার জন্য প্রস্তুত",
    "REPORT_TITLE": "Snaploader Download Report",
    "REPORT_BATCH_INFO": "Batch {{batchNum}} of {{totalBatches}} &bull; Generated on {{date}}",
    "REPORT_STAT_TOTAL": "Total Files",
    "REPORT_STAT_SUCCESSFUL": "Successful",
    "REPORT_STAT_FAILED": "Failed",
    "REPORT_FAILED_MEMORIES_TITLE": "Failed Memories ({{count}})",
    "REPORT_FAILED_MEMORIES_SUBTITLE": "These files could not be downloaded or processed. You may need to request a new data export from Snapchat if the links have expired.",
    "REPORT_FOOTER_TEXT": "Generated by Snaploader &bull; ",
    "REPORT_FOOTER_LINK": "Create your own ZIP",
    "PENDING_GEOCODING": "বিচারাধীন...",
    "COUNTRY_UNKNOWN": "অজানা",
    "MONTH_JANUARY": "জানুয়ারি",
    "MONTH_FEBRUARY": "ফেব্রুয়ারি",
    "MONTH_MARCH": "মার্চ",
    "MONTH_APRIL": "এপ্রিল",
    "MONTH_MAY": "মে",
    "MONTH_JUNE": "জুন",
    "MONTH_JULY": "জুলাই",
    "MONTH_AUGUST": "আগস্ট",
    "MONTH_SEPTEMBER": "সেপ্টেম্বর",
    "MONTH_OCTOBER": "অক্টোবর",
    "MONTH_NOVEMBER": "নভেম্বর",
    "MONTH_DECEMBER": "ডিসেম্বর",
    "Afghanistan": "আফগানিস্তান",
    "Angola": "অ্যাঙ্গোলা",
    "Albania": "আলবেনিয়া",
    "United Arab Emirates": "সংযুক্ত আরব আমিরাত",
    "Argentina": "আর্জেন্টিনা",
    "Armenia": "আর্মেনিয়া",
    "Antarctica": "অ্যান্টার্কটিকা",
    "French Southern and Antarctic Lands": "ফরাসি দক্ষিণ এবং অ্যান্টার্কটিক ভূমি",
    "Australia": "অস্ট্রেলিয়া",
    "Austria": "অস্ট্রিয়া",
    "Azerbaijan": "আজারবাইজান",
    "Burundi": "বুরুন্ডি",
    "Belgium": "বেলজিয়াম",
    "Benin": "বেনিন",
    "Burkina Faso": "বুর্কিনা ফাসো",
    "Bangladesh": "বাংলাদেশ",
    "Bulgaria": "বুলগেরিয়া",
    "The Bahamas": "বাহামা",
    "Bosnia and Herzegovina": "বসনিয়া ও হার্জেগোভিনা",
    "Belarus": "বেলারুশ",
    "Belize": "বেলিজ",
    "Bermuda": "বারমুডা",
    "Bolivia": "বলিভিয়া",
    "Brazil": "ব্রাজিল",
    "Brunei": "ব্রুনাই",
    "Bhutan": "ভুটান",
    "Botswana": "বতসোয়ানা",
    "Central African Republic": "মধ্য আফ্রিকান প্রজাতন্ত্র",
    "Canada": "কানাডা",
    "Switzerland": "সুইজারল্যান্ড",
    "Chile": "চিলি",
    "China": "চীন",
    "Ivory Coast": "আইভরি কোস্ট",
    "Cameroon": "ক্যামেরুন",
    "Democratic Republic of the Congo": "কঙ্গো গণতান্ত্রিক প্রজাতন্ত্র",
    "Republic of the Congo": "কঙ্গো প্রজাতন্ত্র",
    "Colombia": "কলম্বিয়া",
    "Costa Rica": "কোস্টারিকা",
    "Cuba": "কিউবা",
    "Northern Cyprus": "উত্তর সাইপ্রাস",
    "Cyprus": "সাইপ্রাস",
    "Czechia": "চেকিয়া",
    "Germany": "জার্মানি",
    "Djibouti": "জিবুতি",
    "Denmark": "ডেনমার্ক",
    "Dominican Republic": "ডোমিনিকান প্রজাতন্ত্র",
    "Algeria": "আলজেরিয়া",
    "Ecuador": "ইকুয়েডর",
    "Egypt": "মিশর",
    "Eritrea": "ইরিত্রিয়া",
    "Spain": "স্পেন",
    "Estonia": "এস্তোনিয়া",
    "Ethiopia": "ইথিওপিয়া",
    "Finland": "ফিনল্যান্ড",
    "Fiji": "ফিজি",
    "Falkland Islands": "ফকল্যান্ড দ্বীপপুঞ্জ",
    "France": "ফ্রান্স",
    "Gabon": "গ্যাবন",
    "United Kingdom": "যুক্তরাজ্য",
    "Georgia": "জর্জিয়া",
    "Ghana": "ঘানা",
    "Guinea": "গিনি",
    "Gambia": "গাম্বিয়া",
    "Guinea-Bissau": "গিনি-বিসাউ",
    "Equatorial Guinea": "নিরক্ষীয় গিনি",
    "Greece": "গ্রীস",
    "Greenland": "গ্রীনল্যান্ড",
    "Guatemala": "গুয়াতেমালা",
    "Guyana": "গায়ানা",
    "Honduras": "হন্ডুরাস",
    "Croatia": "ক্রোয়েশিয়া",
    "Haiti": "হাইতি",
    "Hungary": "হাঙ্গেরি",
    "Indonesia": "ইন্দোনেশিয়া",
    "India": "ভারত",
    "Ireland": "আয়ারল্যান্ড",
    "Iran": "ইরান",
    "Iraq": "ইরাক",
    "Iceland": "আইসল্যান্ড",
    "Israel": "ইসরায়েল",
    "Italy": "ইতালি",
    "Jamaica": "জামাইকা",
    "Jordan": "জর্ডান",
    "Japan": "জাপান",
    "Kazakhstan": "কাজাখস্তান",
    "Kenya": "কেনিয়া",
    "Kyrgyzstan": "কিরগিজস্তান",
    "Cambodia": "কম্বোডিয়া",
    "South Korea": "দক্ষিণ কোরিয়া",
    "Kosovo": "কসোভো",
    "Kuwait": "কুয়েত",
    "Laos": "লাওস",
    "Lebanon": "লেবানন",
    "Liberia": "লাইবেরিয়া",
    "Libya": "লিবিয়া",
    "Sri Lanka": "শ্রীলঙ্কা",
    "Lesotho": "লেসোথো",
    "Lithuania": "লিথুয়ানিয়া",
    "Luxembourg": "লัก্সেমবার্গ",
    "Latvia": "লাটভিয়া",
    "Morocco": "মরক্কো",
    "Moldova": "মলদোভা",
    "Madagascar": "মাদাগাস্কার",
    "Mexico": "মেক্সিকো",
    "Macedonia": "ম্যাসিডোনিয়া",
    "Mali": "মালি",
    "Myanmar": "মায়ানমার",
    "Montenegro": "মন্টিনিগ্রো",
    "Mongolia": "মঙ্গোলিয়া",
    "Mozambique": "মোজাম্বিক",
    "Mauritania": "মৌরিতানিয়া",
    "Malawi": "মালাউই",
    "Malaysia": "মালয়েশিয়া",
    "Namibia": "নামিবিয়া",
    "New Caledonia": "নতুন ক্যালিডোনিয়া",
    "Niger": "নাইজার",
    "Nigeria": "নাইজেরিয়া",
    "Nicaragua": "নিকারাগুয়া",
    "Netherlands": "নেদারল্যান্ডস",
    "Norway": "নরওয়ে",
    "Nepal": "নেপাল",
    "New Zealand": "নিউজিল্যান্ড",
    "Oman": "ওমান",
    "Pakistan": "পাকিস্তান",
    "Panama": "পানামা",
    "Peru": "পেরু",
    "Philippines": "ফিলিপাইন",
    "Papua New Guinea": "পাপুয়া নিউ গিনি",
    "Poland": "পোল্যান্ড",
    "Puerto Rico": "পুয়ের্তো রিকো",
    "North Korea": "উত্তর কোরিয়া",
    "Portugal": "পর্তুগাল",
    "Paraguay": "প্যারাগুয়ে",
    "Qatar": "কাতার",
    "Romania": "রোমানিয়া",
    "Russia": "রাশিয়া",
    "Rwanda": "রুয়ান্ডা",
    "Western Sahara": "পশ্চিম সাহারা",
    "Saudi Arabia": "সৌদি আরব",
    "Sudan": "সুদান",
    "South Sudan": "দক্ষিণ সুদান",
    "Senegal": "সেনেগাল",
    "Solomon Islands": "সলোমন দ্বীপপুঞ্জ",
    "Sierra Leone": "সিয়েরা লিওন",
    "El Salvador": "এল সালভাদর",
    "Somaliland": "সোমালিল্যান্ড",
    "Somalia": "সোমালিয়া",
    "Republic of Serbia": "সার্বিয়া প্রজাতন্ত্র",
    "Suriname": "সুরিনাম",
    "Slovakia": "স্লোভাকিয়া",
    "Slovenia": "স্লোভেনিয়া",
    "Sweden": "সুইডেন",
    "Swaziland": "সোয়াজিল্যান্ড",
    "Syria": "সিরিয়া",
    "Chad": "চাদ",
    "Togo": "টোগো",
    "Thailand": "থাইল্যান্ড",
    "Tajikistan": "তাজিকিস্তান",
    "Turkmenistan": "তুর্কমেনিস্তান",
    "East Timor": "পূর্ব তিমুর",
    "Trinidad and Tobago": "ত্রিনিদাদ ও টোবাগো",
    "Tunisia": "তিউনিসিয়া",
    "Turkey": "তুরস্ক",
    "Taiwan": "তাইওয়ান",
    "Tanzania": "তানজানিয়া",
    "Uganda": "উগান্ডা",
    "Ukraine": "ইউক্রেন",
    "Uruguay": "উরুগুয়ে",
    "United States of America": "মার্কিন যুক্তরাষ্ট্র",
    "Uzbekistan": "উজবেকিস্তান",
    "Venezuela": "ভেনেজুয়েলা",
    "Vietnam": "ভিয়েতনাম",
    "Vanuatu": "ভানুয়াতু",
    "West Bank": "পশ্চিম তীর",
    "Yemen": "ইয়েমেন",
    "South Africa": "দক্ষিণ আফ্রিকা",
    "Zambia": "জাম্বিয়া",
    "Zimbabwe": "জিম্বাবুয়ে"
  }
};

@Injectable({ providedIn: 'root' })
export class TranslateService {
  private translations = signal<Record<string, string>>({});
  currentLang = signal('en'); // Default language

  // FIX: Added a `ready` computed signal that becomes true once translations are loaded.
  // This resolves the `translateService.ready is not a function` error.
  ready = computed(() => Object.keys(this.translations()).length > 0);

  direction = computed<'ltr' | 'rtl'>(() => {
    const lang = AVAILABLE_LANGUAGES.find(l => l.code === this.currentLang());
    return lang?.dir ?? 'ltr';
  });
  
  availableLanguages = signal(AVAILABLE_LANGUAGES);

  initialize(initialLang: string): void {
    this.use(initialLang);
  }

  use(langCode: string): void {
    const languageData = _translationData[langCode];
    if (languageData) {
      this.translations.set(languageData);
      this.currentLang.set(langCode);
    } else {
      console.warn(`[TranslateService] Language '${langCode}' not found. Falling back to 'en'.`);
      if (langCode !== 'en') {
        this.use('en');
      }
    }
  }

  get(key: string, params?: Record<string, string | number>): string {
    // Use `?? key` to provide a fallback to the key itself if the translation is missing.
    const translation = this.translations()[key] ?? key;
    if (params) {
      return this._interpolate(translation, params);
    }
    return translation;
  }
  
  private _interpolate(text: string, params: Record<string, string | number>): string {
    let interpolated = text;
    for (const [key, value] of Object.entries(params)) {
      const regex = new RegExp(`{{${key}}}`, 'g');
      interpolated = interpolated.replace(regex, String(value));
    }
    return interpolated;
  }
}